// 玻璃（Apple 26）设计系统下 Material Icons → SF 风格 CupertinoIcons 的映射表。
//
// 规则：
// - key 是 Material 图标的 codePoint，只对 `fontFamily == 'MaterialIcons'`（且无
//   fontPackage）的 IconData 生效，查表在 [fushiAppleIcon]（fushi_icon.dart）。
// - Material 的 filled / _outlined / _rounded / _sharp 是不同 codePoint，各自一条：
//   filled 映射到 SF 的 `_fill` 版，outlined 映射到线框版；没有语义对应的不收录，
//   调用点保持 Material 字形，不硬凑一个意思不对的 SF 图标。
// - 本文件由 tmp 下的 gen_icon_map.py 生成（按 fushi/lib 的 Icons.* 使用频次覆盖），
//   手改也行，但要保持 key 唯一（测试会查）。
//
// 为什么只做 codePoint 映射而不改调用点：几千个调用点写的是 `Icons.xxx`，
// 它们同时服务 MD3 与玻璃两套设计系统；MD3 路径必须像素不变，所以不能把源码
// 里的 IconData 换掉，只能在渲染时（[FushiIcon.build]）按设计系统查表替换字形。
// IconData 重写了 `==`，不能当 const Map 的 key，故用 codePoint int。
import 'package:cupertino_ui/cupertino_ui.dart';

/// Material codePoint → CupertinoIcons。注释是对应的 Material 名（同 codePoint 的别名用 / 分隔）。
const Map<int, IconData> kFushiAppleIconMap = <int, IconData>{
  0xe043: CupertinoIcons.person_crop_circle_fill, // account_circle
  0xe047: CupertinoIcons.add, // add
  0xe04f: CupertinoIcons.plus_circle_fill, // add_circle
  0xe050: CupertinoIcons.plus_circle, // add_circle_outline
  0xe053: CupertinoIcons.link, // add_link
  0xe057: CupertinoIcons.photo_on_rectangle, // add_photo_alternate
  0xe078: CupertinoIcons.text_alignleft, // align_horizontal_left
  0xe079: CupertinoIcons.text_alignright, // align_horizontal_right
  0xe080: CupertinoIcons.arrow_branch, // alt_route
  0xe091: CupertinoIcons.archivebox_fill, // archive
  0xe092: CupertinoIcons.chevron_back, // arrow_back
  0xe093: CupertinoIcons.chevron_back, // arrow_back_ios
  0xe097: CupertinoIcons.arrow_down, // arrow_downward
  0xe098: CupertinoIcons.chevron_down, // arrow_drop_down
  0xe09a: CupertinoIcons.chevron_up, // arrow_drop_up
  0xe09b: CupertinoIcons.chevron_forward, // arrow_forward
  0xe09c: CupertinoIcons.chevron_forward, // arrow_forward_ios
  0xe09d: CupertinoIcons.arrowtriangle_left_fill, // arrow_left
  0xe09e: CupertinoIcons.arrowtriangle_right_fill, // arrow_right
  0xe0a0: CupertinoIcons.arrow_up, // arrow_upward
  0xe0a2: CupertinoIcons.doc_text_fill, // article
  0xe0a3:
      CupertinoIcons.rectangle_arrow_up_right_arrow_down_left, // aspect_ratio
  0xe0b6: CupertinoIcons.music_note, // audiotrack
  0xe0b7: CupertinoIcons.sparkles, // auto_awesome
  0xe0bb: CupertinoIcons.wand_stars, // auto_fix_high
  0xe0bf: CupertinoIcons.book_fill, // auto_stories
  0xe0c1: CupertinoIcons.arrow_2_circlepath, // autorenew
  0xe0c6: CupertinoIcons.cloud_upload_fill, // backup
  0xe0c8: CupertinoIcons.person_crop_rectangle_fill, // badge
  0xe0cc: CupertinoIcons.chart_bar_fill, // bar_chart
  0xe0e1: CupertinoIcons.nosign, // block
  0xe0ee: CupertinoIcons.bolt_fill, // bolt
  0xe0ef: CupertinoIcons.book_fill, // book
  0xe0f1: CupertinoIcons.bookmark_fill, // bookmark
  0xe0f2: CupertinoIcons.bookmark_fill, // bookmark_add
  0xe0f4: CupertinoIcons.bookmark, // bookmark_border / bookmark_outline
  0xe0f6: CupertinoIcons.bookmark_fill, // bookmarks
  0xe0fa: CupertinoIcons.pencil, // border_color
  0xe10a: CupertinoIcons.sun_max_fill, // brightness_6
  0xe10b: CupertinoIcons.sun_max_fill, // brightness_7
  0xe10c: CupertinoIcons.sun_max_fill, // brightness_auto
  0xe10d: CupertinoIcons.sun_max_fill, // brightness_high
  0xe10e: CupertinoIcons.sun_min, // brightness_low
  0xe10f: CupertinoIcons.sun_max, // brightness_medium
  0xe113: CupertinoIcons.paintbrush_fill, // brush
  0xe115: CupertinoIcons.ant_fill, // bug_report
  0xe117: CupertinoIcons.wrench_fill, // build_circle
  0xe11f: CupertinoIcons.arrow_2_circlepath, // cached
  0xe122: CupertinoIcons.calendar_today, // calendar_today
  0xe12d: CupertinoIcons.arrow_branch, // call_split
  0xe130: CupertinoIcons.camera_fill, // camera_alt
  0xe139: CupertinoIcons.xmark_circle_fill, // cancel
  0xe144: CupertinoIcons.tv, // cast
  0xe145: CupertinoIcons.tv_fill, // cast_connected
  0xe156: CupertinoIcons.checkmark, // check
  0xe157: CupertinoIcons.checkmark_square_fill, // check_box
  0xe158: CupertinoIcons.square, // check_box_outline_blank
  0xe159: CupertinoIcons.checkmark_circle_fill, // check_circle
  0xe15a: CupertinoIcons.checkmark_circle, // check_circle_outline
  0xe15b: CupertinoIcons.checkmark_square, // checklist
  0xe15e: CupertinoIcons.chevron_left, // chevron_left
  0xe15f: CupertinoIcons.chevron_right, // chevron_right
  0xe162: CupertinoIcons.book_fill, // chrome_reader_mode
  0xe163: CupertinoIcons.circle_fill, // circle
  0xe168: CupertinoIcons.xmark, // clear
  0xe16a: CupertinoIcons.xmark, // close
  0xe16b: CupertinoIcons.arrow_down_right_arrow_up_left, // close_fullscreen
  0xe16c: CupertinoIcons.captions_bubble_fill, // closed_caption
  0xe16f: CupertinoIcons.cloud_fill, // cloud
  0xe171: CupertinoIcons.cloud_fill, // cloud_done
  0xe172: CupertinoIcons.cloud_download_fill, // cloud_download
  0xe173: CupertinoIcons.wifi_slash, // cloud_off
  0xe175: CupertinoIcons.cloud_upload_fill, // cloud_upload
  0xe176: CupertinoIcons.chevron_left_slash_chevron_right, // code
  0xe17a: CupertinoIcons.photo_on_rectangle, // collections
  0xe17b: CupertinoIcons.bookmark_fill, // collections_bookmark
  0xe17c: CupertinoIcons.paintbrush_fill, // color_lens
  0xe17d: CupertinoIcons.eyedropper_full, // colorize
  0xe182: CupertinoIcons.arrow_right_arrow_left, // compare_arrows
  0xe185: CupertinoIcons.desktopcomputer, // computer
  0xe190: CupertinoIcons.doc_on_doc_fill, // content_copy / copy
  0xe192: CupertinoIcons.doc_on_clipboard_fill, // content_paste
  0xe197: CupertinoIcons.doc_on_doc_fill, // copy_all
  0xe19e: CupertinoIcons.folder_badge_plus, // create_new_folder
  0xe1a3: CupertinoIcons.crop, // crop
  0xe1a9: CupertinoIcons.viewfinder, // crop_free
  0xe1ae: CupertinoIcons.square_fill, // crop_square
  0xe1b0: CupertinoIcons.moon_fill, // dark_mode
  0xe1b1: CupertinoIcons.square_grid_2x2_fill, // dashboard
  0xe1b2: CupertinoIcons.square_grid_2x2_fill, // dashboard_customize
  0xe1b6: CupertinoIcons.calendar, // date_range
  0xe1b8: CupertinoIcons.line_horizontal_3, // dehaze
  0xe1b9: CupertinoIcons.trash_fill, // delete
  0xe1ba: CupertinoIcons.trash_fill, // delete_forever
  0xe1bb: CupertinoIcons.trash, // delete_outline
  0xe1bc: CupertinoIcons.trash_fill, // delete_sweep
  0xe1bf: CupertinoIcons.doc_text_fill, // description
  0xe1c3: CupertinoIcons.desktopcomputer, // desktop_windows
  0xe1cb: CupertinoIcons.device_laptop, // devices
  0xe1cc: CupertinoIcons.device_laptop, // devices_other
  0xe1e5: CupertinoIcons.rectangle_grid_1x2_fill, // dns
  0xe1ed: CupertinoIcons.minus_circle_fill, // do_not_disturb_on
  0xe1f2: CupertinoIcons.doc_text_viewfinder, // document_scanner
  0xe1f6: CupertinoIcons.checkmark, // done
  0xe1f7: CupertinoIcons.checkmark_alt, // done_all
  0xe201: CupertinoIcons.arrow_down_circle_fill, // download
  0xe202: CupertinoIcons.checkmark_circle_fill, // download_done
  0xe204: CupertinoIcons.arrow_down_circle_fill, // downloading
  0xe206: CupertinoIcons.line_horizontal_3, // drag_handle
  0xe207: CupertinoIcons.line_horizontal_3, // drag_indicator
  0xe209: CupertinoIcons.folder_fill, // drive_file_move
  0xe20a: CupertinoIcons.folder, // drive_file_move_outline
  0xe20b: CupertinoIcons.square_pencil, // drive_file_rename_outline
  0xe21a: CupertinoIcons.pencil, // edit
  0xe22c: CupertinoIcons.rosette, // emoji_events
  0xe237: CupertinoIcons.exclamationmark_circle_fill, // error
  0xe238: CupertinoIcons.exclamationmark_circle, // error_outline
  0xe23f: CupertinoIcons.calendar, // event_available
  0xe241: CupertinoIcons.calendar, // event_note
  0xe243: CupertinoIcons.square_arrow_right_fill, // exit_to_app
  0xe245: CupertinoIcons.chevron_up, // expand_less
  0xe246: CupertinoIcons.chevron_down, // expand_more
  0xe248: CupertinoIcons.compass_fill, // explore
  0xe250: CupertinoIcons.cube_box_fill, // extension
  0xe256: CupertinoIcons.doc_checkmark_fill, // fact_check
  0xe258: CupertinoIcons.forward_fill, // fast_forward
  0xe259: CupertinoIcons.backward_fill, // fast_rewind
  0xe25b: CupertinoIcons.heart_fill, // favorite
  0xe25c: CupertinoIcons.heart, // favorite_border
  0xe26a: CupertinoIcons.arrow_down_doc_fill, // file_download
  0xe26e: CupertinoIcons.arrow_up_doc_fill, // file_upload
  0xe27a: CupertinoIcons.line_horizontal_3_decrease_circle_fill, // filter_alt
  0xe27b: CupertinoIcons.circle_lefthalf_fill, // filter_b_and_w
  0xe280: CupertinoIcons.line_horizontal_3_decrease, // filter_list
  0xe28b: CupertinoIcons.arrow_left_to_line, // first_page
  0xe28c: CupertinoIcons.rectangle_arrow_up_right_arrow_down_left, // fit_screen
  0xe28e: CupertinoIcons.flag_fill, // flag
  0xe2a3: CupertinoIcons.folder_fill, // folder
  0xe2a4: CupertinoIcons.folder_open, // folder_open
  0xe2a8: CupertinoIcons.textformat, // font_download
  0xe2ab: CupertinoIcons.text_aligncenter, // format_align_center
  0xe2ad: CupertinoIcons.text_alignleft, // format_align_left
  0xe2ae: CupertinoIcons.text_alignright, // format_align_right
  0xe2af: CupertinoIcons.bold, // format_bold
  0xe2b5: CupertinoIcons.increase_indent, // format_indent_increase
  0xe2b8: CupertinoIcons.list_bullet, // format_list_bulleted
  0xe2b9: CupertinoIcons.list_number, // format_list_numbered
  0xe2bc: CupertinoIcons.quote_bubble_fill, // format_quote
  0xe2be: CupertinoIcons.textformat_size, // format_size
  0xe2c3: CupertinoIcons.chat_bubble_2_fill, // forum
  0xe2c5: CupertinoIcons.goforward_10, // forward_10
  0xe2cb: CupertinoIcons.fullscreen, // fullscreen
  0xe2cc: CupertinoIcons.fullscreen_exit, // fullscreen_exit
  0xe2d0: CupertinoIcons.gamecontroller_fill, // gamepad
  0xe2e3: CupertinoIcons.waveform, // graphic_eq / multitrack_audio
  0xe2ea: CupertinoIcons.square_grid_2x2_fill, // grid_view
  0xe2eb: CupertinoIcons.person_2_fill, // group
  0xe2ff: CupertinoIcons.headphones, // headphones
  0xe308: CupertinoIcons.arrow_up_down, // height
  0xe30b: CupertinoIcons.question_circle, // help_outline
  0xe314: CupertinoIcons.clock, // history
  0xe316: CupertinoIcons.clock, // history_toggle_off
  0xe318: CupertinoIcons.house_fill, // home
  0xe31f: CupertinoIcons.minus, // horizontal_rule
  0xe325: CupertinoIcons.hourglass, // hourglass_empty
  0xe327: CupertinoIcons.hourglass, // hourglass_top
  0xe32b: CupertinoIcons.person_crop_circle_badge_checkmark, // how_to_reg
  0xe332: CupertinoIcons.photo_fill, // image
  0xe337: CupertinoIcons.book_fill, // import_contacts
  0xe33c: CupertinoIcons.info_circle_fill, // info
  0xe33d: CupertinoIcons.info_circle, // info_outline
  0xe33f: CupertinoIcons.chart_bar_square_fill, // insert_chart
  0xe342: CupertinoIcons.doc_fill, // insert_drive_file
  0xe347: CupertinoIcons.chart_bar_fill, // insights
  0xe34a: CupertinoIcons.archivebox_fill, // inventory_2
  0xe34b: CupertinoIcons.drop_fill, // invert_colors
  0xe34d: CupertinoIcons.share, // ios_share
  0xe351: CupertinoIcons.keyboard, // keyboard
  0xe352: CupertinoIcons.keyboard, // keyboard_alt
  0xe353: CupertinoIcons.chevron_down, // keyboard_arrow_down
  0xe354: CupertinoIcons.chevron_left, // keyboard_arrow_left
  0xe355: CupertinoIcons.chevron_right, // keyboard_arrow_right
  0xe356: CupertinoIcons.chevron_up, // keyboard_arrow_up
  0xe364: CupertinoIcons.tag, // label_outline
  0xe366: CupertinoIcons.globe, // language
  0xe36b: CupertinoIcons.arrow_right_to_line, // last_page
  0xe36f: CupertinoIcons.chart_bar_fill, // leaderboard
  0xe375: CupertinoIcons.plus_rectangle_on_rectangle, // library_add
  0xe376: CupertinoIcons.checkmark_square_fill, // library_add_check
  0xe377: CupertinoIcons.book_fill, // library_books
  0xe378: CupertinoIcons.music_albums_fill, // library_music
  0xe37a: CupertinoIcons.sun_max_fill, // light_mode
  0xe37c: CupertinoIcons.lightbulb, // lightbulb_outline
  0xe380: CupertinoIcons.link, // link
  0xe384: CupertinoIcons.list_bullet, // list
  0xe385: CupertinoIcons.list_bullet, // list_alt
  0xe387: CupertinoIcons.tv_fill, // live_tv
  0xe392: CupertinoIcons.flame_fill, // local_fire_department
  0xe3ae: CupertinoIcons.lock_fill, // lock
  0xe3b0: CupertinoIcons.lock_open_fill, // lock_open
  0xe3b1: CupertinoIcons.lock, // lock_outline
  0xe3b2: CupertinoIcons.arrow_right_to_line, // login
  0xe3b3: CupertinoIcons.square_arrow_right, // logout
  0xe3c6: CupertinoIcons.person_crop_circle_fill, // manage_accounts
  0xe3c7: CupertinoIcons.doc_text_search, // manage_search
  0xe3d0: CupertinoIcons.envelope_badge_fill, // mark_email_unread
  0xe3dd: CupertinoIcons.book_fill, // menu_book
  0xe3de: CupertinoIcons.sidebar_left, // menu_open
  0xe3df: CupertinoIcons.arrow_merge, // merge_type
  0xe3e1: CupertinoIcons.mic_fill, // mic
  0xe3e4: CupertinoIcons.mic_fill, // mic_none
  0xe3e8: CupertinoIcons.minus, // minimize
  0xe402: CupertinoIcons.ellipsis, // more_horiz
  0xe404: CupertinoIcons.ellipsis_vertical, // more_vert
  0xe40c: CupertinoIcons.tray_arrow_down_fill, // move_to_inbox
  0xe40d: CupertinoIcons.film_fill, // movie
  0xe40e: CupertinoIcons.film_fill, // movie_creation
  0xe40f: CupertinoIcons.film_fill, // movie_filter
  0xe415: CupertinoIcons.music_note, // music_note
  0xe418: CupertinoIcons.location_fill, // my_location
  0xe424: CupertinoIcons.wifi, // network_check
  0xe427: CupertinoIcons.tag_fill, // new_label
  0xe44a: CupertinoIcons.doc_append, // note_add
  0xe44f: CupertinoIcons.bell_fill, // notifications
  0xe450: CupertinoIcons.bell_fill, // notifications_active
  0xe451: CupertinoIcons.bell_fill, // notifications_none
  0xe452: CupertinoIcons.bell_slash_fill, // notifications_off
  0xe459: CupertinoIcons.drop_fill, // opacity
  0xe45b: CupertinoIcons.arrow_up_left_arrow_down_right, // open_in_full
  0xe45c: CupertinoIcons.arrow_up_right_square, // open_in_new
  0xe45e: CupertinoIcons.move, // open_with
  0xe462: CupertinoIcons.tray_arrow_up_fill, // outbox
  0xe46b: CupertinoIcons.paintbrush_fill, // palette
  0xe47c: CupertinoIcons.pause_fill, // pause
  0xe47e: CupertinoIcons.pause_circle_fill, // pause_circle_filled
  0xe47f: CupertinoIcons.pause_circle, // pause_circle_outline
  0xe487: CupertinoIcons.person_2_fill, // people_alt
  0xe488: CupertinoIcons.person_2, // people_outline
  0xe48e: CupertinoIcons.photo_on_rectangle, // perm_media
  0xe491: CupertinoIcons.person_fill, // person
  0xe493: CupertinoIcons.person_badge_plus_fill, // person_add_alt
  0xe494: CupertinoIcons.person_badge_plus_fill, // person_add_alt_1
  0xe497: CupertinoIcons.person, // person_outline
  0xe49a: CupertinoIcons.person_badge_minus_fill, // person_remove
  0xe4a3: CupertinoIcons.device_phone_portrait, // phone_android
  0xe4b6: CupertinoIcons.camera_fill, // photo_camera
  0xe4b7: CupertinoIcons.camera_fill, // photo_camera_back
  0xe4ba: CupertinoIcons.photo_fill_on_rectangle_fill, // photo_library
  0xe4c0: CupertinoIcons.doc_fill, // picture_as_pdf
  0xe4c2: CupertinoIcons.rectangle_on_rectangle, // picture_in_picture_alt
  0xe4c5: CupertinoIcons.chart_pie, // pie_chart_outline
  0xe4cb: CupertinoIcons.play_fill, // play_arrow
  0xe4cc: CupertinoIcons.play_circle_fill, // play_circle
  0xe4cd: CupertinoIcons.play_circle_fill, // play_circle_filled
  0xe4ce: CupertinoIcons.play_circle, // play_circle_outline
  0xe4d2: CupertinoIcons.text_badge_plus, // playlist_add
  0xe4d3: CupertinoIcons.text_badge_checkmark, // playlist_add_check
  0xe4d4: CupertinoIcons.music_note_list, // playlist_play
  0xe4ed: CupertinoIcons.shield_lefthalf_fill, // privacy_tip
  0xe4f0: CupertinoIcons.globe, // public
  0xe4f4: CupertinoIcons.pin_fill, // push_pin
  0xe4f6: CupertinoIcons.qrcode, // qr_code_2
  0xe4f7: CupertinoIcons.qrcode_viewfinder, // qr_code_scanner
  0xe4fc: CupertinoIcons.music_note_list, // queue_music
  0xe503: CupertinoIcons.largecircle_fill_circle, // radio_button_checked
  0xe504: CupertinoIcons.circle, // radio_button_off / radio_button_unchecked
  0xe50d: CupertinoIcons.doc_text_fill, // receipt_long
  0xe514: CupertinoIcons.arrow_clockwise, // refresh
  0xe516: CupertinoIcons.minus, // remove
  0xe518: CupertinoIcons.minus_circle, // remove_circle_outline
  0xe51f: CupertinoIcons.repeat, // repeat
  0xe523: CupertinoIcons.gobackward, // replay
  0xe524: CupertinoIcons.gobackward_10, // replay_10
  0xe52d: CupertinoIcons.exclamationmark_triangle_fill, // report_problem
  0xe531: CupertinoIcons.arrow_counterclockwise, // restart_alt
  0xe534: CupertinoIcons.arrow_counterclockwise, // restore
  0xe542: CupertinoIcons.antenna_radiowaves_left_right, // router
  0xe550: CupertinoIcons.floppy_disk, // save
  0xe551: CupertinoIcons.tray_arrow_down_fill, // save_alt
  0xe556: CupertinoIcons.clock_fill, // schedule
  0xe55a: CupertinoIcons.lab_flask, // science
  0xe567: CupertinoIcons.search, // search
  0xe569: CupertinoIcons.shield_fill, // security
  0xe56d: CupertinoIcons.text_alignleft, // segment
  0xe570: CupertinoIcons.tag_fill, // sell
  0xe571: CupertinoIcons.paperplane_fill, // send
  0xe576: CupertinoIcons.antenna_radiowaves_left_right, // sensors
  0xe57f: CupertinoIcons.gear_solid, // settings
  0xe582: CupertinoIcons.arrow_counterclockwise, // settings_backup_restore
  0xe590: CupertinoIcons.gear, // settings_suggest
  0xe593: CupertinoIcons.share, // share
  0xe596: CupertinoIcons.shield_fill, // shield
  0xe59d: CupertinoIcons.text_alignleft, // short_text
  0xe59f: CupertinoIcons.graph_square, // show_chart
  0xe5bd: CupertinoIcons.forward_end_fill, // skip_next
  0xe5be: CupertinoIcons.backward_end_fill, // skip_previous
  0xe5c3: CupertinoIcons.play_rectangle_fill, // smart_display
  0xe5c6: CupertinoIcons.device_phone_portrait, // smartphone
  0xe5d2: CupertinoIcons.sort_down, // sort
  0xe5d3: CupertinoIcons.textformat_abc, // sort_by_alpha
  0xe5d5: CupertinoIcons.arrow_down, // south
  0xe5dd: CupertinoIcons.text_bubble_fill, // speaker_notes
  0xe5e0: CupertinoIcons.speedometer, // speed
  0xe5e8: CupertinoIcons.gamecontroller_fill, // sports_esports
  0xe5f6: CupertinoIcons.chart_bar_fill, // stacked_bar_chart
  0xe5f9: CupertinoIcons.star_fill, // star
  0xe5fa: CupertinoIcons.star, // star_border
  0xe5fd: CupertinoIcons.star, // star_outline
  0xe606: CupertinoIcons.stop_fill, // stop
  0xe607: CupertinoIcons.stop_circle_fill, // stop_circle
  0xe613: CupertinoIcons.paintbrush_fill, // style
  0xe616: CupertinoIcons.text_alignleft, // subject
  0xe618: CupertinoIcons.rectangle_stack_fill, // subscriptions
  0xe619: CupertinoIcons.captions_bubble_fill, // subtitles
  0xe625: CupertinoIcons.arrow_right_arrow_left, // swap_horiz
  0xe626: CupertinoIcons
      .arrow_right_arrow_left_circle_fill, // swap_horizontal_circle
  0xe627: CupertinoIcons.arrow_up_arrow_down, // swap_vert
  0xe629: CupertinoIcons.hand_draw_fill, // swipe
  0xe62f: CupertinoIcons.arrow_2_circlepath, // sync
  0xe630: CupertinoIcons.arrow_right_arrow_left, // sync_alt
  0xe636: CupertinoIcons.tray_arrow_down, // system_update
  0xe637: CupertinoIcons.tray_arrow_down, // system_update_alt
  0xe640: CupertinoIcons.number, // tag
  0xe649: CupertinoIcons.textformat, // text_fields
  0xe662: CupertinoIcons.timer_fill, // timer
  0xe668: CupertinoIcons.textformat, // title
  0xe66a: CupertinoIcons.calendar_today, // today
  0xe670: CupertinoIcons.hand_point_right_fill, // touch_app
  0xe67b: CupertinoIcons.globe, // translate
  0xe67c: CupertinoIcons.globe, // travel_explore
  0xe683: CupertinoIcons.slider_horizontal_3, // tune
  0xe687: CupertinoIcons.tv_fill, // tv
  0xe68c: CupertinoIcons.arrow_uturn_left, // undo
  0xe68e: CupertinoIcons.chevron_up_chevron_down, // unfold_more
  0xe692: CupertinoIcons.arrow_clockwise, // update
  0xe695: CupertinoIcons.arrow_up_circle_fill, // upload
  0xe696: CupertinoIcons.arrow_up_doc_fill, // upload_file
  0xe699: CupertinoIcons.checkmark_seal_fill, // verified
  0xe69a: CupertinoIcons.checkmark_shield_fill, // verified_user
  0xe69b: CupertinoIcons.arrow_down_to_line, // vertical_align_bottom
  0xe69d: CupertinoIcons.arrow_up_to_line, // vertical_align_top
  0xe6a5: CupertinoIcons.film_fill, // video_library
  0xe6a8: CupertinoIcons.videocam_fill, // videocam
  0xe6aa: CupertinoIcons.gamecontroller_fill, // videogame_asset
  0xe6ac: CupertinoIcons.rectangle_grid_1x2_fill, // view_agenda
  0xe6af: CupertinoIcons.rectangle_split_3x1_fill, // view_column
  0xe6b2: CupertinoIcons.rectangle_grid_1x2_fill, // view_day
  0xe6b5: CupertinoIcons.list_bullet, // view_list
  0xe6b8: CupertinoIcons.sidebar_left, // view_sidebar
  0xe6b9: CupertinoIcons.rectangle_grid_1x2_fill, // view_stream
  0xe6bd: CupertinoIcons.eye_fill, // visibility
  0xe6be: CupertinoIcons.eye_slash_fill, // visibility_off
  0xe6c2: CupertinoIcons.speaker_1_fill, // volume_down
  0xe6c4: CupertinoIcons.speaker_slash_fill, // volume_off
  0xe6c5: CupertinoIcons.speaker_2_fill, // volume_up
  0xe6c7: CupertinoIcons.lock_fill, // vpn_key
  0xe6cb: CupertinoIcons.exclamationmark_triangle_fill, // warning
  0xe6cc: CupertinoIcons.exclamationmark_triangle, // warning_amber
  0xe6de: CupertinoIcons.macwindow, // web_asset
  0xe6e6: CupertinoIcons.square_grid_2x2_fill, // widgets
  0xe6ed: CupertinoIcons.antenna_radiowaves_left_right, // wifi_tethering
  0xe6fd: CupertinoIcons.zoom_in, // zoom_in
  0xe6fe: CupertinoIcons.zoom_out, // zoom_out
  0xe6ff: CupertinoIcons.arrow_up_left_arrow_down_right, // zoom_out_map
  0xe743: CupertinoIcons.person_crop_circle_fill, // account_circle_sharp
  0xe74d: CupertinoIcons.plus_circle, // add_circle_outline_sharp
  0xe74e: CupertinoIcons.plus_circle_fill, // add_circle_sharp
  0xe751: CupertinoIcons.link, // add_link_sharp
  0xe755: CupertinoIcons.photo_on_rectangle, // add_photo_alternate_sharp
  0xe758: CupertinoIcons.add, // add_sharp
  0xe777: CupertinoIcons.text_alignleft, // align_horizontal_left_sharp
  0xe778: CupertinoIcons.text_alignright, // align_horizontal_right_sharp
  0xe77f: CupertinoIcons.arrow_branch, // alt_route_sharp
  0xe790: CupertinoIcons.archivebox_fill, // archive_sharp
  0xe792: CupertinoIcons.chevron_back, // arrow_back_ios_sharp
  0xe793: CupertinoIcons.chevron_back, // arrow_back_sharp
  0xe796: CupertinoIcons.arrow_down, // arrow_downward_sharp
  0xe798: CupertinoIcons.chevron_down, // arrow_drop_down_sharp
  0xe799: CupertinoIcons.chevron_up, // arrow_drop_up_sharp
  0xe79a: CupertinoIcons.chevron_forward, // arrow_forward_ios_sharp
  0xe79b: CupertinoIcons.chevron_forward, // arrow_forward_sharp
  0xe79c: CupertinoIcons.arrowtriangle_left_fill, // arrow_left_sharp
  0xe79e: CupertinoIcons.arrowtriangle_right_fill, // arrow_right_sharp
  0xe79f: CupertinoIcons.arrow_up, // arrow_upward_sharp
  0xe7a1: CupertinoIcons.doc_text_fill, // article_sharp
  0xe7a2: CupertinoIcons
      .rectangle_arrow_up_right_arrow_down_left, // aspect_ratio_sharp
  0xe7b4: CupertinoIcons.music_note, // audiotrack_sharp
  0xe7b7: CupertinoIcons.sparkles, // auto_awesome_sharp
  0xe7b9: CupertinoIcons.wand_stars, // auto_fix_high_sharp
  0xe7bd: CupertinoIcons.book_fill, // auto_stories_sharp
  0xe7bf: CupertinoIcons.arrow_2_circlepath, // autorenew_sharp
  0xe7c4: CupertinoIcons.cloud_upload_fill, // backup_sharp
  0xe7c6: CupertinoIcons.person_crop_rectangle_fill, // badge_sharp
  0xe7ca: CupertinoIcons.chart_bar_fill, // bar_chart_sharp
  0xe7df: CupertinoIcons.nosign, // block_sharp
  0xe7eb: CupertinoIcons.bolt_fill, // bolt_sharp
  0xe7ed: CupertinoIcons.book_fill, // book_sharp
  0xe7ee: CupertinoIcons.bookmark_fill, // bookmark_add_sharp
  0xe7f0:
      CupertinoIcons.bookmark, // bookmark_border_sharp / bookmark_outline_sharp
  0xe7f2: CupertinoIcons.bookmark_fill, // bookmark_sharp
  0xe7f3: CupertinoIcons.bookmark_fill, // bookmarks_sharp
  0xe7f7: CupertinoIcons.pencil, // border_color_sharp
  0xe807: CupertinoIcons.sun_max_fill, // brightness_6_sharp
  0xe808: CupertinoIcons.sun_max_fill, // brightness_7_sharp
  0xe809: CupertinoIcons.sun_max_fill, // brightness_auto_sharp
  0xe80a: CupertinoIcons.sun_max_fill, // brightness_high_sharp
  0xe80b: CupertinoIcons.sun_min, // brightness_low_sharp
  0xe80c: CupertinoIcons.sun_max, // brightness_medium_sharp
  0xe810: CupertinoIcons.paintbrush_fill, // brush_sharp
  0xe812: CupertinoIcons.ant_fill, // bug_report_sharp
  0xe813: CupertinoIcons.wrench_fill, // build_circle_sharp
  0xe81c: CupertinoIcons.arrow_2_circlepath, // cached_sharp
  0xe81f: CupertinoIcons.calendar_today, // calendar_today_sharp
  0xe82a: CupertinoIcons.arrow_branch, // call_split_sharp
  0xe82c: CupertinoIcons.camera_fill, // camera_alt_sharp
  0xe838: CupertinoIcons.xmark_circle_fill, // cancel_sharp
  0xe841: CupertinoIcons.tv_fill, // cast_connected_sharp
  0xe843: CupertinoIcons.tv, // cast_sharp
  0xe853: CupertinoIcons.square, // check_box_outline_blank_sharp
  0xe854: CupertinoIcons.checkmark_square_fill, // check_box_sharp
  0xe855: CupertinoIcons.checkmark_circle, // check_circle_outline_sharp
  0xe856: CupertinoIcons.checkmark_circle_fill, // check_circle_sharp
  0xe857: CupertinoIcons.checkmark, // check_sharp
  0xe859: CupertinoIcons.checkmark_square_fill, // checklist_sharp
  0xe85b: CupertinoIcons.chevron_left, // chevron_left_sharp
  0xe85c: CupertinoIcons.chevron_right, // chevron_right_sharp
  0xe85f: CupertinoIcons.book_fill, // chrome_reader_mode_sharp
  0xe861: CupertinoIcons.circle_fill, // circle_sharp
  0xe866: CupertinoIcons.xmark, // clear_sharp
  0xe867:
      CupertinoIcons.arrow_down_right_arrow_up_left, // close_fullscreen_sharp
  0xe868: CupertinoIcons.xmark, // close_sharp
  0xe86b: CupertinoIcons.captions_bubble_fill, // closed_caption_sharp
  0xe86d: CupertinoIcons.cloud_fill, // cloud_done_sharp
  0xe86e: CupertinoIcons.cloud_download_fill, // cloud_download_sharp
  0xe86f: CupertinoIcons.wifi_slash, // cloud_off_sharp
  0xe871: CupertinoIcons.cloud_fill, // cloud_sharp
  0xe872: CupertinoIcons.cloud_upload_fill, // cloud_upload_sharp
  0xe874: CupertinoIcons.chevron_left_slash_chevron_right, // code_sharp
  0xe877: CupertinoIcons.bookmark_fill, // collections_bookmark_sharp
  0xe878: CupertinoIcons.photo_on_rectangle, // collections_sharp
  0xe879: CupertinoIcons.paintbrush_fill, // color_lens_sharp
  0xe87a: CupertinoIcons.eyedropper_full, // colorize_sharp
  0xe87e: CupertinoIcons.arrow_right_arrow_left, // compare_arrows_sharp
  0xe882: CupertinoIcons.desktopcomputer, // computer_sharp
  0xe88d: CupertinoIcons.doc_on_doc_fill, // content_copy_sharp / copy_sharp
  0xe890: CupertinoIcons.doc_on_clipboard_fill, // content_paste_sharp
  0xe894: CupertinoIcons.doc_on_doc_fill, // copy_all_sharp
  0xe89a: CupertinoIcons.folder_badge_plus, // create_new_folder_sharp
  0xe8a5: CupertinoIcons.viewfinder, // crop_free_sharp
  0xe8aa: CupertinoIcons.crop, // crop_sharp
  0xe8ab: CupertinoIcons.square_fill, // crop_square_sharp
  0xe8ad: CupertinoIcons.moon_fill, // dark_mode_sharp
  0xe8ae: CupertinoIcons.square_grid_2x2_fill, // dashboard_customize_sharp
  0xe8af: CupertinoIcons.square_grid_2x2_fill, // dashboard_sharp
  0xe8b3: CupertinoIcons.calendar, // date_range_sharp
  0xe8b5: CupertinoIcons.line_horizontal_3, // dehaze_sharp
  0xe8b6: CupertinoIcons.trash_fill, // delete_forever_sharp
  0xe8b7: CupertinoIcons.trash, // delete_outline_sharp
  0xe8b8: CupertinoIcons.trash_fill, // delete_sharp
  0xe8b9: CupertinoIcons.trash_fill, // delete_sweep_sharp
  0xe8bc: CupertinoIcons.doc_text_fill, // description_sharp
  0xe8c0: CupertinoIcons.desktopcomputer, // desktop_windows_sharp
  0xe8c8: CupertinoIcons.device_laptop, // devices_other_sharp
  0xe8c9: CupertinoIcons.device_laptop, // devices_sharp
  0xe8e2: CupertinoIcons.rectangle_grid_1x2_fill, // dns_sharp
  0xe8e9: CupertinoIcons.minus_circle_fill, // do_not_disturb_on_sharp
  0xe8ef: CupertinoIcons.doc_text_viewfinder, // document_scanner_sharp
  0xe8f3: CupertinoIcons.checkmark_alt, // done_all_sharp
  0xe8f5: CupertinoIcons.checkmark, // done_sharp
  0xe8fe: CupertinoIcons.checkmark_circle_fill, // download_done_sharp
  0xe900: CupertinoIcons.arrow_down_circle_fill, // download_sharp
  0xe901: CupertinoIcons.arrow_down_circle_fill, // downloading_sharp
  0xe903: CupertinoIcons.line_horizontal_3, // drag_handle_sharp
  0xe904: CupertinoIcons.line_horizontal_3, // drag_indicator_sharp
  0xe906: CupertinoIcons.folder_fill, // drive_file_move_sharp
  0xe907: CupertinoIcons.square_pencil, // drive_file_rename_outline_sharp
  0xe91c: CupertinoIcons.pencil, // edit_sharp
  0xe928: CupertinoIcons.rosette, // emoji_events_sharp
  0xe933: CupertinoIcons.exclamationmark_circle, // error_outline_sharp
  0xe934: CupertinoIcons.exclamationmark_circle_fill, // error_sharp
  0xe93a: CupertinoIcons.calendar, // event_available_sharp
  0xe93c: CupertinoIcons.calendar, // event_note_sharp
  0xe93f: CupertinoIcons.square_arrow_right_fill, // exit_to_app_sharp
  0xe940: CupertinoIcons.chevron_up, // expand_less_sharp
  0xe941: CupertinoIcons.chevron_down, // expand_more_sharp
  0xe945: CupertinoIcons.compass_fill, // explore_sharp
  0xe94d: CupertinoIcons.cube_box_fill, // extension_sharp
  0xe953: CupertinoIcons.doc_checkmark_fill, // fact_check_sharp
  0xe955: CupertinoIcons.forward_fill, // fast_forward_sharp
  0xe956: CupertinoIcons.backward_fill, // fast_rewind_sharp
  0xe958: CupertinoIcons.heart, // favorite_border_sharp
  0xe959: CupertinoIcons.heart_fill, // favorite_sharp
  0xe969: CupertinoIcons.arrow_down_doc_fill, // file_download_sharp
  0xe96b: CupertinoIcons.arrow_up_doc_fill, // file_upload_sharp
  0xe976:
      CupertinoIcons.line_horizontal_3_decrease_circle_fill, // filter_alt_sharp
  0xe977: CupertinoIcons.circle_lefthalf_fill, // filter_b_and_w_sharp
  0xe97c: CupertinoIcons.line_horizontal_3_decrease, // filter_list_sharp
  0xe986: CupertinoIcons.arrow_left_to_line, // first_page_sharp
  0xe987: CupertinoIcons
      .rectangle_arrow_up_right_arrow_down_left, // fit_screen_sharp
  0xe989: CupertinoIcons.flag_fill, // flag_sharp
  0xe99e: CupertinoIcons.folder_open, // folder_open_sharp
  0xe9a0: CupertinoIcons.folder_fill, // folder_sharp
  0xe9a4: CupertinoIcons.textformat, // font_download_sharp
  0xe9a6: CupertinoIcons.text_aligncenter, // format_align_center_sharp
  0xe9a8: CupertinoIcons.text_alignleft, // format_align_left_sharp
  0xe9a9: CupertinoIcons.text_alignright, // format_align_right_sharp
  0xe9aa: CupertinoIcons.bold, // format_bold_sharp
  0xe9b0: CupertinoIcons.increase_indent, // format_indent_increase_sharp
  0xe9b3: CupertinoIcons.list_bullet, // format_list_bulleted_sharp
  0xe9b5: CupertinoIcons.list_number, // format_list_numbered_sharp
  0xe9b7: CupertinoIcons.quote_bubble_fill, // format_quote_sharp
  0xe9b9: CupertinoIcons.textformat_size, // format_size_sharp
  0xe9be: CupertinoIcons.chat_bubble_2_fill, // forum_sharp
  0xe9bf: CupertinoIcons.goforward_10, // forward_10_sharp
  0xe9c6: CupertinoIcons.fullscreen_exit, // fullscreen_exit_sharp
  0xe9c7: CupertinoIcons.fullscreen, // fullscreen_sharp
  0xe9cb: CupertinoIcons.gamecontroller_fill, // gamepad_sharp
  0xe9de: CupertinoIcons.waveform, // graphic_eq_sharp / multitrack_audio_sharp
  0xe9e5: CupertinoIcons.square_grid_2x2_fill, // grid_view_sharp
  0xe9e7: CupertinoIcons.person_2_fill, // group_sharp
  0xe9fb: CupertinoIcons.headphones, // headphones_sharp
  0xea03: CupertinoIcons.arrow_up_down, // height_sharp
  0xea05: CupertinoIcons.question_circle, // help_outline_sharp
  0xea10: CupertinoIcons.clock, // history_sharp
  0xea11: CupertinoIcons.clock, // history_toggle_off_sharp
  0xea16: CupertinoIcons.house_fill, // home_sharp
  0xea19: CupertinoIcons.minus, // horizontal_rule_sharp
  0xea1f: CupertinoIcons.hourglass, // hourglass_empty_sharp
  0xea21: CupertinoIcons.hourglass, // hourglass_top_sharp
  0xea25: CupertinoIcons.person_crop_circle_badge_checkmark, // how_to_reg_sharp
  0xea2f: CupertinoIcons.photo_fill, // image_sharp
  0xea31: CupertinoIcons.book_fill, // import_contacts_sharp
  0xea36: CupertinoIcons.info_circle, // info_outline_sharp
  0xea37: CupertinoIcons.info_circle_fill, // info_sharp
  0xea3a: CupertinoIcons.chart_bar_square_fill, // insert_chart_sharp
  0xea3c: CupertinoIcons.doc_fill, // insert_drive_file_sharp
  0xea41: CupertinoIcons.chart_bar_fill, // insights_sharp
  0xea43: CupertinoIcons.archivebox_fill, // inventory_2_sharp
  0xea46: CupertinoIcons.drop_fill, // invert_colors_sharp
  0xea47: CupertinoIcons.share, // ios_share_sharp
  0xea4b: CupertinoIcons.keyboard, // keyboard_alt_sharp
  0xea4c: CupertinoIcons.chevron_down, // keyboard_arrow_down_sharp
  0xea4d: CupertinoIcons.chevron_left, // keyboard_arrow_left_sharp
  0xea4e: CupertinoIcons.chevron_right, // keyboard_arrow_right_sharp
  0xea4f: CupertinoIcons.chevron_up, // keyboard_arrow_up_sharp
  0xea54: CupertinoIcons.keyboard, // keyboard_sharp
  0xea5d: CupertinoIcons.tag, // label_outline_sharp
  0xea60: CupertinoIcons.globe, // language_sharp
  0xea65: CupertinoIcons.arrow_right_to_line, // last_page_sharp
  0xea69: CupertinoIcons.chart_bar_fill, // leaderboard_sharp
  0xea6f: CupertinoIcons.checkmark_square_fill, // library_add_check_sharp
  0xea70: CupertinoIcons.plus_rectangle_on_rectangle, // library_add_sharp
  0xea71: CupertinoIcons.book_fill, // library_books_sharp
  0xea72: CupertinoIcons.music_albums_fill, // library_music_sharp
  0xea73: CupertinoIcons.sun_max_fill, // light_mode_sharp
  0xea75: CupertinoIcons.lightbulb, // lightbulb_outline_sharp
  0xea7b: CupertinoIcons.link, // link_sharp
  0xea7e: CupertinoIcons.list_bullet, // list_alt_sharp
  0xea7f: CupertinoIcons.list_bullet, // list_sharp
  0xea81: CupertinoIcons.tv_fill, // live_tv_sharp
  0xea8c: CupertinoIcons.flame_fill, // local_fire_department_sharp
  0xeaa8: CupertinoIcons.lock_open_fill, // lock_open_sharp
  0xeaa9: CupertinoIcons.lock, // lock_outline_sharp
  0xeaaa: CupertinoIcons.lock_fill, // lock_sharp
  0xeaab: CupertinoIcons.arrow_right_to_line, // login_sharp
  0xeaac: CupertinoIcons.square_arrow_right, // logout_sharp
  0xeabf: CupertinoIcons.person_crop_circle_fill, // manage_accounts_sharp
  0xeac0: CupertinoIcons.doc_text_search, // manage_search_sharp
  0xeac9: CupertinoIcons.envelope_badge_fill, // mark_email_unread_sharp
  0xead5: CupertinoIcons.book_fill, // menu_book_sharp
  0xead6: CupertinoIcons.sidebar_left, // menu_open_sharp
  0xead8: CupertinoIcons.arrow_merge, // merge_type_sharp
  0xeadc: CupertinoIcons.mic_fill, // mic_none_sharp
  0xeade: CupertinoIcons.mic_fill, // mic_sharp
  0xeae1: CupertinoIcons.minus, // minimize_sharp
  0xeafa: CupertinoIcons.ellipsis, // more_horiz_sharp
  0xeafd: CupertinoIcons.ellipsis_vertical, // more_vert_sharp
  0xeb05: CupertinoIcons.tray_arrow_down_fill, // move_to_inbox_sharp
  0xeb06: CupertinoIcons.film_fill, // movie_creation_sharp
  0xeb07: CupertinoIcons.film_fill, // movie_filter_sharp
  0xeb08: CupertinoIcons.film_fill, // movie_sharp
  0xeb0e: CupertinoIcons.music_note, // music_note_sharp
  0xeb11: CupertinoIcons.location_fill, // my_location_sharp
  0xeb1d: CupertinoIcons.wifi, // network_check_sharp
  0xeb20: CupertinoIcons.tag_fill, // new_label_sharp
  0xeb41: CupertinoIcons.doc_append, // note_add_sharp
  0xeb47: CupertinoIcons.bell_fill, // notifications_active_sharp
  0xeb48: CupertinoIcons.bell_fill, // notifications_none_sharp
  0xeb49: CupertinoIcons.bell_slash_fill, // notifications_off_sharp
  0xeb4b: CupertinoIcons.bell_fill, // notifications_sharp
  0xeb51: CupertinoIcons.drop_fill, // opacity_sharp
  0xeb53: CupertinoIcons.arrow_up_left_arrow_down_right, // open_in_full_sharp
  0xeb55: CupertinoIcons.arrow_up_right_square, // open_in_new_sharp
  0xeb56: CupertinoIcons.move, // open_with_sharp
  0xeb5a: CupertinoIcons.tray_arrow_up_fill, // outbox_sharp
  0xeb62: CupertinoIcons.paintbrush_fill, // palette_sharp
  0xeb73: CupertinoIcons.pause_circle_fill, // pause_circle_filled_sharp
  0xeb74: CupertinoIcons.pause_circle, // pause_circle_outline_sharp
  0xeb77: CupertinoIcons.pause_fill, // pause_sharp
  0xeb7d: CupertinoIcons.person_2_fill, // people_alt_sharp
  0xeb7e: CupertinoIcons.person_2, // people_outline_sharp
  0xeb85: CupertinoIcons.photo_on_rectangle, // perm_media_sharp
  0xeb88: CupertinoIcons.person_badge_plus_fill, // person_add_alt_1_sharp
  0xeb89: CupertinoIcons.person_badge_plus_fill, // person_add_alt_sharp
  0xeb8d: CupertinoIcons.person, // person_outline_sharp
  0xeb91: CupertinoIcons.person_badge_minus_fill, // person_remove_sharp
  0xeb93: CupertinoIcons.person_fill, // person_sharp
  0xeb99: CupertinoIcons.device_phone_portrait, // phone_android_sharp
  0xebac: CupertinoIcons.camera_fill, // photo_camera_back_sharp
  0xebae: CupertinoIcons.camera_fill, // photo_camera_sharp
  0xebb0: CupertinoIcons.photo_on_rectangle, // photo_library_sharp
  0xebb7: CupertinoIcons.doc_fill, // picture_as_pdf_sharp
  0xebb8: CupertinoIcons.rectangle_on_rectangle, // picture_in_picture_alt_sharp
  0xebba: CupertinoIcons.chart_pie, // pie_chart_outline_sharp
  0xebc1: CupertinoIcons.play_fill, // play_arrow_sharp
  0xebc2: CupertinoIcons.play_circle_fill, // play_circle_filled_sharp
  0xebc3: CupertinoIcons.play_circle, // play_circle_outline_sharp
  0xebc4: CupertinoIcons.play_circle_fill, // play_circle_sharp
  0xebc8: CupertinoIcons.text_badge_checkmark, // playlist_add_check_sharp
  0xebc9: CupertinoIcons.text_badge_plus, // playlist_add_sharp
  0xebca: CupertinoIcons.music_note_list, // playlist_play_sharp
  0xebe3: CupertinoIcons.shield_lefthalf_fill, // privacy_tip_sharp
  0xebe7: CupertinoIcons.globe, // public_sharp
  0xebea: CupertinoIcons.pin_fill, // push_pin_sharp
  0xebeb: CupertinoIcons.qrcode, // qr_code_2_sharp
  0xebec: CupertinoIcons.qrcode_viewfinder, // qr_code_scanner_sharp
  0xebf1: CupertinoIcons.music_note_list, // queue_music_sharp
  0xebf8: CupertinoIcons.largecircle_fill_circle, // radio_button_checked_sharp
  0xebf9: CupertinoIcons
      .circle, // radio_button_off_sharp / radio_button_unchecked_sharp
  0xec02: CupertinoIcons.doc_text_fill, // receipt_long_sharp
  0xec0a: CupertinoIcons.arrow_clockwise, // refresh_sharp
  0xec0c: CupertinoIcons.minus_circle, // remove_circle_outline_sharp
  0xec12: CupertinoIcons.minus, // remove_sharp
  0xec18: CupertinoIcons.repeat, // repeat_sharp
  0xec19: CupertinoIcons.gobackward_10, // replay_10_sharp
  0xec1d: CupertinoIcons.gobackward, // replay_sharp
  0xec22: CupertinoIcons.exclamationmark_triangle_fill, // report_problem_sharp
  0xec27: CupertinoIcons.arrow_counterclockwise, // restart_alt_sharp
  0xec2c: CupertinoIcons.arrow_counterclockwise, // restore_sharp
  0xec38: CupertinoIcons.antenna_radiowaves_left_right, // router_sharp
  0xec46: CupertinoIcons.tray_arrow_down_fill, // save_alt_sharp
  0xec47: CupertinoIcons.floppy_disk, // save_sharp
  0xec4d: CupertinoIcons.clock_fill, // schedule_sharp
  0xec50: CupertinoIcons.lab_flask, // science_sharp
  0xec5e: CupertinoIcons.search, // search_sharp
  0xec5f: CupertinoIcons.shield_fill, // security_sharp
  0xec63: CupertinoIcons.text_alignleft, // segment_sharp
  0xec66: CupertinoIcons.tag_fill, // sell_sharp
  0xec68: CupertinoIcons.paperplane_fill, // send_sharp
  0xec6d: CupertinoIcons.antenna_radiowaves_left_right, // sensors_sharp
  0xec77:
      CupertinoIcons.arrow_counterclockwise, // settings_backup_restore_sharp
  0xec85: CupertinoIcons.gear, // settings_sharp
  0xec86: CupertinoIcons.gear, // settings_suggest_sharp
  0xec8b: CupertinoIcons.share, // share_sharp
  0xec8c: CupertinoIcons.shield_fill, // shield_sharp
  0xec93: CupertinoIcons.text_alignleft, // short_text_sharp
  0xec95: CupertinoIcons.graph_square, // show_chart_sharp
  0xecb3: CupertinoIcons.forward_end_fill, // skip_next_sharp
  0xecb4: CupertinoIcons.backward_end_fill, // skip_previous_sharp
  0xecb9: CupertinoIcons.play_rectangle_fill, // smart_display_sharp
  0xecbc: CupertinoIcons.device_phone_portrait, // smartphone_sharp
  0xecc8: CupertinoIcons.textformat_abc, // sort_by_alpha_sharp
  0xecc9: CupertinoIcons.sort_down, // sort_sharp
  0xeccc: CupertinoIcons.arrow_down, // south_sharp
  0xecd3: CupertinoIcons.text_bubble_fill, // speaker_notes_sharp
  0xecd6: CupertinoIcons.speedometer, // speed_sharp
  0xecdd: CupertinoIcons.gamecontroller_fill, // sports_esports_sharp
  0xecec: CupertinoIcons.chart_bar_fill, // stacked_bar_chart_sharp
  0xecf0: CupertinoIcons.star, // star_border_sharp
  0xecf2: CupertinoIcons.star, // star_outline_sharp
  0xecf5: CupertinoIcons.star_fill, // star_sharp
  0xecfc: CupertinoIcons.stop_circle_fill, // stop_circle_sharp
  0xecfe: CupertinoIcons.stop_fill, // stop_sharp
  0xed09: CupertinoIcons.paintbrush_fill, // style_sharp
  0xed0c: CupertinoIcons.text_alignleft, // subject_sharp
  0xed0e: CupertinoIcons.rectangle_stack_fill, // subscriptions_sharp
  0xed10: CupertinoIcons.captions_bubble_fill, // subtitles_sharp
  0xed1b: CupertinoIcons.arrow_right_arrow_left, // swap_horiz_sharp
  0xed1c: CupertinoIcons
      .arrow_right_arrow_left_circle_fill, // swap_horizontal_circle_sharp
  0xed1d: CupertinoIcons.arrow_up_arrow_down, // swap_vert_sharp
  0xed1f: CupertinoIcons.hand_draw_fill, // swipe_sharp
  0xed25: CupertinoIcons.arrow_right_arrow_left, // sync_alt_sharp
  0xed28: CupertinoIcons.arrow_2_circlepath, // sync_sharp
  0xed2c: CupertinoIcons.tray_arrow_down, // system_update_alt_sharp
  0xed2d: CupertinoIcons.tray_arrow_down, // system_update_sharp
  0xed37: CupertinoIcons.number, // tag_sharp
  0xed3f: CupertinoIcons.textformat, // text_fields_sharp
  0xed5d: CupertinoIcons.timer_fill, // timer_sharp
  0xed5e: CupertinoIcons.textformat, // title_sharp
  0xed60: CupertinoIcons.calendar_today, // today_sharp
  0xed66: CupertinoIcons.hand_point_right_fill, // touch_app_sharp
  0xed71: CupertinoIcons.globe, // translate_sharp
  0xed72: CupertinoIcons.globe, // travel_explore_sharp
  0xed79: CupertinoIcons.slider_horizontal_3, // tune_sharp
  0xed7e: CupertinoIcons.tv_fill, // tv_sharp
  0xed82: CupertinoIcons.arrow_uturn_left, // undo_sharp
  0xed84: CupertinoIcons.chevron_up_chevron_down, // unfold_more_sharp
  0xed89: CupertinoIcons.arrow_clockwise, // update_sharp
  0xed8b: CupertinoIcons.arrow_up_doc_fill, // upload_file_sharp
  0xed8c: CupertinoIcons.arrow_up_circle_fill, // upload_sharp
  0xed8f: CupertinoIcons.checkmark_seal_fill, // verified_sharp
  0xed90: CupertinoIcons.checkmark_shield_fill, // verified_user_sharp
  0xed91: CupertinoIcons.arrow_down_to_line, // vertical_align_bottom_sharp
  0xed93: CupertinoIcons.arrow_up_to_line, // vertical_align_top_sharp
  0xed9b: CupertinoIcons.film_fill, // video_library_sharp
  0xed9f: CupertinoIcons.videocam_fill, // videocam_sharp
  0xeda1: CupertinoIcons.gamecontroller_fill, // videogame_asset_sharp
  0xeda2: CupertinoIcons.rectangle_grid_1x2_fill, // view_agenda_sharp
  0xeda5: CupertinoIcons.rectangle_split_3x1_fill, // view_column_sharp
  0xeda8: CupertinoIcons.rectangle_grid_1x2_fill, // view_day_sharp
  0xedab: CupertinoIcons.list_bullet, // view_list_sharp
  0xedae: CupertinoIcons.sidebar_left, // view_sidebar_sharp
  0xedaf: CupertinoIcons.rectangle_grid_1x2_fill, // view_stream_sharp
  0xedb3: CupertinoIcons.eye_slash_fill, // visibility_off_sharp
  0xedb4: CupertinoIcons.eye_fill, // visibility_sharp
  0xedb8: CupertinoIcons.speaker_1_fill, // volume_down_sharp
  0xedba: CupertinoIcons.speaker_slash_fill, // volume_off_sharp
  0xedbb: CupertinoIcons.speaker_2_fill, // volume_up_sharp
  0xedbd: CupertinoIcons.lock_fill, // vpn_key_sharp
  0xedc1: CupertinoIcons.exclamationmark_triangle_fill, // warning_amber_sharp
  0xedc2: CupertinoIcons.exclamationmark_triangle_fill, // warning_sharp
  0xedd3: CupertinoIcons.macwindow, // web_asset_sharp
  0xedda: CupertinoIcons.square_grid_2x2_fill, // widgets_sharp
  0xede3: CupertinoIcons.antenna_radiowaves_left_right, // wifi_tethering_sharp
  0xedef: CupertinoIcons.zoom_in, // zoom_in_sharp
  0xedf0: CupertinoIcons.arrow_up_left_arrow_down_right, // zoom_out_map_sharp
  0xedf1: CupertinoIcons.zoom_out, // zoom_out_sharp
  0xee35: CupertinoIcons.person_crop_circle, // account_circle_outlined
  0xee3f: CupertinoIcons.plus_circle, // add_circle_outline_outlined
  0xee40: CupertinoIcons.plus_circle, // add_circle_outlined
  0xee43: CupertinoIcons.link, // add_link_outlined
  0xee47: CupertinoIcons.add, // add_outlined
  0xee48: CupertinoIcons.photo_on_rectangle, // add_photo_alternate_outlined
  0xee69: CupertinoIcons.text_alignleft, // align_horizontal_left_outlined
  0xee6a: CupertinoIcons.text_alignright, // align_horizontal_right_outlined
  0xee71: CupertinoIcons.arrow_branch, // alt_route_outlined
  0xee82: CupertinoIcons.archivebox, // archive_outlined
  0xee84: CupertinoIcons.chevron_back, // arrow_back_ios_outlined
  0xee85: CupertinoIcons.chevron_back, // arrow_back_outlined
  0xee88: CupertinoIcons.arrow_down, // arrow_downward_outlined
  0xee8a: CupertinoIcons.chevron_down, // arrow_drop_down_outlined
  0xee8b: CupertinoIcons.chevron_up, // arrow_drop_up_outlined
  0xee8c: CupertinoIcons.chevron_forward, // arrow_forward_ios_outlined
  0xee8d: CupertinoIcons.chevron_forward, // arrow_forward_outlined
  0xee8e: CupertinoIcons.arrowtriangle_left, // arrow_left_outlined
  0xee90: CupertinoIcons.arrowtriangle_right, // arrow_right_outlined
  0xee91: CupertinoIcons.arrow_up, // arrow_upward_outlined
  0xee93: CupertinoIcons.doc_text, // article_outlined
  0xee94: CupertinoIcons
      .rectangle_arrow_up_right_arrow_down_left, // aspect_ratio_outlined
  0xeea6: CupertinoIcons.music_note, // audiotrack_outlined
  0xeea9: CupertinoIcons.sparkles, // auto_awesome_outlined
  0xeeab: CupertinoIcons.wand_stars, // auto_fix_high_outlined
  0xeeaf: CupertinoIcons.book, // auto_stories_outlined
  0xeeb1: CupertinoIcons.arrow_2_circlepath, // autorenew_outlined
  0xeeb6: CupertinoIcons.cloud_upload, // backup_outlined
  0xeeb8: CupertinoIcons.person_crop_rectangle, // badge_outlined
  0xeebc: CupertinoIcons.chart_bar, // bar_chart_outlined
  0xeed1: CupertinoIcons.nosign, // block_outlined
  0xeedd: CupertinoIcons.bolt, // bolt_outlined
  0xeedf: CupertinoIcons.book, // book_outlined
  0xeee0: CupertinoIcons.bookmark, // bookmark_add_outlined
  0xeee2: CupertinoIcons
      .bookmark, // bookmark_border_outlined / bookmark_outline_outlined
  0xeee3: CupertinoIcons.bookmark, // bookmark_outlined
  0xeee5: CupertinoIcons.bookmark, // bookmarks_outlined
  0xeee9: CupertinoIcons.pencil, // border_color_outlined
  0xeef9: CupertinoIcons.sun_max, // brightness_6_outlined
  0xeefa: CupertinoIcons.sun_max, // brightness_7_outlined
  0xeefb: CupertinoIcons.sun_max, // brightness_auto_outlined
  0xeefc: CupertinoIcons.sun_max, // brightness_high_outlined
  0xeefd: CupertinoIcons.sun_min, // brightness_low_outlined
  0xeefe: CupertinoIcons.sun_max, // brightness_medium_outlined
  0xef02: CupertinoIcons.paintbrush, // brush_outlined
  0xef04: CupertinoIcons.ant, // bug_report_outlined
  0xef05: CupertinoIcons.wrench, // build_circle_outlined
  0xef0e: CupertinoIcons.arrow_2_circlepath, // cached_outlined
  0xef11: CupertinoIcons.calendar_today, // calendar_today_outlined
  0xef1c: CupertinoIcons.arrow_branch, // call_split_outlined
  0xef1e: CupertinoIcons.camera, // camera_alt_outlined
  0xef28: CupertinoIcons.xmark_circle, // cancel_outlined
  0xef33: CupertinoIcons.tv, // cast_connected_outlined
  0xef35: CupertinoIcons.tv, // cast_outlined
  0xef45: CupertinoIcons.square, // check_box_outline_blank_outlined
  0xef46: CupertinoIcons.checkmark_square, // check_box_outlined
  0xef47: CupertinoIcons.checkmark_circle, // check_circle_outline_outlined
  0xef48: CupertinoIcons.checkmark_circle, // check_circle_outlined
  0xef49: CupertinoIcons.checkmark, // check_outlined
  0xef4a: CupertinoIcons.checkmark_square, // checklist_outlined
  0xef4d: CupertinoIcons.chevron_left, // chevron_left_outlined
  0xef4e: CupertinoIcons.chevron_right, // chevron_right_outlined
  0xef51: CupertinoIcons.book, // chrome_reader_mode_outlined
  0xef53: CupertinoIcons.circle, // circle_outlined
  0xef58: CupertinoIcons.xmark, // clear_outlined
  0xef59: CupertinoIcons
      .arrow_down_right_arrow_up_left, // close_fullscreen_outlined
  0xef5a: CupertinoIcons.xmark, // close_outlined
  0xef5d: CupertinoIcons.captions_bubble, // closed_caption_outlined
  0xef5f: CupertinoIcons.cloud, // cloud_done_outlined
  0xef60: CupertinoIcons.cloud_download, // cloud_download_outlined
  0xef61: CupertinoIcons.wifi_slash, // cloud_off_outlined
  0xef62: CupertinoIcons.cloud, // cloud_outlined
  0xef64: CupertinoIcons.cloud_upload, // cloud_upload_outlined
  0xef66: CupertinoIcons.chevron_left_slash_chevron_right, // code_outlined
  0xef69: CupertinoIcons.bookmark, // collections_bookmark_outlined
  0xef6a: CupertinoIcons.photo_on_rectangle, // collections_outlined
  0xef6b: CupertinoIcons.paintbrush, // color_lens_outlined
  0xef6c: CupertinoIcons.eyedropper, // colorize_outlined
  0xef70: CupertinoIcons.arrow_right_arrow_left, // compare_arrows_outlined
  0xef74: CupertinoIcons.desktopcomputer, // computer_outlined
  0xef7f: CupertinoIcons.doc_on_doc, // content_copy_outlined / copy_outlined
  0xef82: CupertinoIcons.doc_on_clipboard, // content_paste_outlined
  0xef86: CupertinoIcons.doc_on_doc, // copy_all_outlined
  0xef8c: CupertinoIcons.folder_badge_plus, // create_new_folder_outlined
  0xef97: CupertinoIcons.viewfinder, // crop_free_outlined
  0xef9a: CupertinoIcons.crop, // crop_outlined
  0xef9d: CupertinoIcons.square, // crop_square_outlined
  0xef9f: CupertinoIcons.moon, // dark_mode_outlined
  0xefa0: CupertinoIcons.square_grid_2x2, // dashboard_customize_outlined
  0xefa1: CupertinoIcons.square_grid_2x2, // dashboard_outlined
  0xefa5: CupertinoIcons.calendar, // date_range_outlined
  0xefa7: CupertinoIcons.line_horizontal_3, // dehaze_outlined
  0xefa8: CupertinoIcons.trash, // delete_forever_outlined
  0xefa9: CupertinoIcons.trash, // delete_outline_outlined
  0xefaa: CupertinoIcons.trash, // delete_outlined
  0xefab: CupertinoIcons.trash, // delete_sweep_outlined
  0xefae: CupertinoIcons.doc_text, // description_outlined
  0xefb2: CupertinoIcons.desktopcomputer, // desktop_windows_outlined
  0xefba: CupertinoIcons.device_laptop, // devices_other_outlined
  0xefbb: CupertinoIcons.device_laptop, // devices_outlined
  0xefd4: CupertinoIcons.rectangle_grid_1x2, // dns_outlined
  0xefdb: CupertinoIcons.minus_circle, // do_not_disturb_on_outlined
  0xefe1: CupertinoIcons.doc_text_viewfinder, // document_scanner_outlined
  0xefe5: CupertinoIcons.checkmark_alt, // done_all_outlined
  0xefe7: CupertinoIcons.checkmark, // done_outlined
  0xeff0: CupertinoIcons.checkmark_circle, // download_done_outlined
  0xeff2: CupertinoIcons.arrow_down_circle, // download_outlined
  0xeff3: CupertinoIcons.arrow_down_circle, // downloading_outlined
  0xeff5: CupertinoIcons.line_horizontal_3, // drag_handle_outlined
  0xeff6: CupertinoIcons.line_horizontal_3, // drag_indicator_outlined
  0xeff8: CupertinoIcons.folder, // drive_file_move_outlined
  0xeff9: CupertinoIcons.square_pencil, // drive_file_rename_outline_outlined
  0xf00d: CupertinoIcons.pencil, // edit_outlined
  0xf01a: CupertinoIcons.rosette, // emoji_events_outlined
  0xf025: CupertinoIcons.exclamationmark_circle, // error_outline_outlined
  0xf026: CupertinoIcons.exclamationmark_circle, // error_outlined
  0xf02c: CupertinoIcons.calendar, // event_available_outlined
  0xf02e: CupertinoIcons.calendar, // event_note_outlined
  0xf031: CupertinoIcons.square_arrow_right, // exit_to_app_outlined
  0xf032: CupertinoIcons.chevron_up, // expand_less_outlined
  0xf033: CupertinoIcons.chevron_down, // expand_more_outlined
  0xf037: CupertinoIcons.compass, // explore_outlined
  0xf03f: CupertinoIcons.cube_box, // extension_outlined
  0xf045: CupertinoIcons.doc_checkmark, // fact_check_outlined
  0xf047: CupertinoIcons.forward, // fast_forward_outlined
  0xf048: CupertinoIcons.backward, // fast_rewind_outlined
  0xf04a: CupertinoIcons.heart, // favorite_border_outlined
  0xf04b: CupertinoIcons.heart, // favorite_outlined
  0xf05b: CupertinoIcons.arrow_down_doc, // file_download_outlined
  0xf05d: CupertinoIcons.arrow_up_doc, // file_upload_outlined
  0xf068:
      CupertinoIcons.line_horizontal_3_decrease_circle, // filter_alt_outlined
  0xf069: CupertinoIcons.circle_lefthalf_fill, // filter_b_and_w_outlined
  0xf06e: CupertinoIcons.line_horizontal_3_decrease, // filter_list_outlined
  0xf078: CupertinoIcons.arrow_left_to_line, // first_page_outlined
  0xf079: CupertinoIcons
      .rectangle_arrow_up_right_arrow_down_left, // fit_screen_outlined
  0xf07b: CupertinoIcons.flag, // flag_outlined
  0xf090: CupertinoIcons.folder_open, // folder_open_outlined
  0xf091: CupertinoIcons.folder, // folder_outlined
  0xf096: CupertinoIcons.textformat, // font_download_outlined
  0xf098: CupertinoIcons.text_aligncenter, // format_align_center_outlined
  0xf09a: CupertinoIcons.text_alignleft, // format_align_left_outlined
  0xf09b: CupertinoIcons.text_alignright, // format_align_right_outlined
  0xf09c: CupertinoIcons.bold, // format_bold_outlined
  0xf0a2: CupertinoIcons.increase_indent, // format_indent_increase_outlined
  0xf0a5: CupertinoIcons.list_bullet, // format_list_bulleted_outlined
  0xf0a6: CupertinoIcons.list_number, // format_list_numbered_outlined
  0xf0a9: CupertinoIcons.quote_bubble, // format_quote_outlined
  0xf0ab: CupertinoIcons.textformat_size, // format_size_outlined
  0xf0b0: CupertinoIcons.chat_bubble_2, // forum_outlined
  0xf0b1: CupertinoIcons.goforward_10, // forward_10_outlined
  0xf0b8: CupertinoIcons.fullscreen_exit, // fullscreen_exit_outlined
  0xf0b9: CupertinoIcons.fullscreen, // fullscreen_outlined
  0xf0bd: CupertinoIcons.gamecontroller, // gamepad_outlined
  0xf0d0: CupertinoIcons
      .waveform, // graphic_eq_outlined / multitrack_audio_outlined
  0xf0d7: CupertinoIcons.square_grid_2x2, // grid_view_outlined
  0xf0d9: CupertinoIcons.person_2, // group_outlined
  0xf0ed: CupertinoIcons.headphones, // headphones_outlined
  0xf0f5: CupertinoIcons.arrow_up_down, // height_outlined
  0xf0f7: CupertinoIcons.question_circle, // help_outline_outlined
  0xf102: CupertinoIcons.clock, // history_outlined
  0xf103: CupertinoIcons.clock, // history_toggle_off_outlined
  0xf107: CupertinoIcons.house, // home_outlined
  0xf10b: CupertinoIcons.minus, // horizontal_rule_outlined
  0xf111: CupertinoIcons.hourglass, // hourglass_empty_outlined
  0xf113: CupertinoIcons.hourglass, // hourglass_top_outlined
  0xf117:
      CupertinoIcons.person_crop_circle_badge_checkmark, // how_to_reg_outlined
  0xf120: CupertinoIcons.photo, // image_outlined
  0xf123: CupertinoIcons.book, // import_contacts_outlined
  0xf128: CupertinoIcons.info_circle, // info_outlined
  0xf12a: CupertinoIcons.chart_bar_square, // insert_chart_outlined
  0xf12d: CupertinoIcons.doc, // insert_drive_file_outlined
  0xf132: CupertinoIcons.chart_bar, // insights_outlined
  0xf134: CupertinoIcons.archivebox, // inventory_2_outlined
  0xf137: CupertinoIcons.drop, // invert_colors_outlined
  0xf138: CupertinoIcons.share, // ios_share_outlined
  0xf13c: CupertinoIcons.keyboard, // keyboard_alt_outlined
  0xf13d: CupertinoIcons.chevron_down, // keyboard_arrow_down_outlined
  0xf13e: CupertinoIcons.chevron_left, // keyboard_arrow_left_outlined
  0xf13f: CupertinoIcons.chevron_right, // keyboard_arrow_right_outlined
  0xf140: CupertinoIcons.chevron_up, // keyboard_arrow_up_outlined
  0xf144: CupertinoIcons.keyboard, // keyboard_outlined
  0xf14f: CupertinoIcons.globe, // language_outlined
  0xf154: CupertinoIcons.arrow_right_to_line, // last_page_outlined
  0xf158: CupertinoIcons.chart_bar, // leaderboard_outlined
  0xf15e: CupertinoIcons.checkmark_square, // library_add_check_outlined
  0xf15f: CupertinoIcons.plus_rectangle_on_rectangle, // library_add_outlined
  0xf160: CupertinoIcons.book, // library_books_outlined
  0xf161: CupertinoIcons.music_albums, // library_music_outlined
  0xf162: CupertinoIcons.sun_max, // light_mode_outlined
  0xf169: CupertinoIcons.link, // link_outlined
  0xf16c: CupertinoIcons.list_bullet, // list_alt_outlined
  0xf16d: CupertinoIcons.list_bullet, // list_outlined
  0xf16f: CupertinoIcons.tv, // live_tv_outlined
  0xf17a: CupertinoIcons.flame, // local_fire_department_outlined
  0xf196: CupertinoIcons.lock_open, // lock_open_outlined
  0xf197: CupertinoIcons.lock, // lock_outlined
  0xf198: CupertinoIcons.arrow_right_to_line, // login_outlined
  0xf199: CupertinoIcons.square_arrow_right, // logout_outlined
  0xf1ac: CupertinoIcons.person_crop_circle, // manage_accounts_outlined
  0xf1ad: CupertinoIcons.doc_text_search, // manage_search_outlined
  0xf1b6: CupertinoIcons.envelope_badge, // mark_email_unread_outlined
  0xf1c2: CupertinoIcons.book, // menu_book_outlined
  0xf1c3: CupertinoIcons.sidebar_left, // menu_open_outlined
  0xf1c5: CupertinoIcons.arrow_merge, // merge_type_outlined
  0xf1c9: CupertinoIcons.mic, // mic_none_outlined
  0xf1cb: CupertinoIcons.mic, // mic_outlined
  0xf1ce: CupertinoIcons.minus, // minimize_outlined
  0xf1e7: CupertinoIcons.ellipsis, // more_horiz_outlined
  0xf1ea: CupertinoIcons.ellipsis_vertical, // more_vert_outlined
  0xf1f2: CupertinoIcons.tray_arrow_down, // move_to_inbox_outlined
  0xf1f3: CupertinoIcons.film, // movie_creation_outlined
  0xf1f4: CupertinoIcons.film, // movie_filter_outlined
  0xf1f5: CupertinoIcons.film, // movie_outlined
  0xf1fb: CupertinoIcons.music_note, // music_note_outlined
  0xf1fe: CupertinoIcons.location, // my_location_outlined
  0xf20a: CupertinoIcons.wifi, // network_check_outlined
  0xf20d: CupertinoIcons.tag, // new_label_outlined
  0xf22e: CupertinoIcons.doc_append, // note_add_outlined
  0xf234: CupertinoIcons.bell, // notifications_active_outlined
  0xf235: CupertinoIcons.bell, // notifications_none_outlined
  0xf236: CupertinoIcons.bell_slash, // notifications_off_outlined
  0xf237: CupertinoIcons.bell, // notifications_outlined
  0xf23e: CupertinoIcons.drop, // opacity_outlined
  0xf240:
      CupertinoIcons.arrow_up_left_arrow_down_right, // open_in_full_outlined
  0xf242: CupertinoIcons.arrow_up_right_square, // open_in_new_outlined
  0xf243: CupertinoIcons.move, // open_with_outlined
  0xf247: CupertinoIcons.tray_arrow_up, // outbox_outlined
  0xf24f: CupertinoIcons.paintbrush, // palette_outlined
  0xf260: CupertinoIcons.pause_circle, // pause_circle_filled_outlined
  0xf261: CupertinoIcons.pause_circle, // pause_circle_outline_outlined
  0xf263: CupertinoIcons.pause, // pause_outlined
  0xf26a: CupertinoIcons.person_2, // people_alt_outlined
  0xf26b: CupertinoIcons.person_2, // people_outline_outlined
  0xf272: CupertinoIcons.photo_on_rectangle, // perm_media_outlined
  0xf275: CupertinoIcons.person_badge_plus, // person_add_alt_1_outlined
  0xf276: CupertinoIcons.person_badge_plus, // person_add_alt_outlined
  0xf27a: CupertinoIcons.person, // person_outline_outlined
  0xf27b: CupertinoIcons.person, // person_outlined
  0xf27f: CupertinoIcons.person_badge_minus, // person_remove_outlined
  0xf286: CupertinoIcons.device_phone_portrait, // phone_android_outlined
  0xf299: CupertinoIcons.camera, // photo_camera_back_outlined
  0xf29b: CupertinoIcons.camera, // photo_camera_outlined
  0xf29d: CupertinoIcons.photo_on_rectangle, // photo_library_outlined
  0xf2a4: CupertinoIcons.doc, // picture_as_pdf_outlined
  0xf2a5:
      CupertinoIcons.rectangle_on_rectangle, // picture_in_picture_alt_outlined
  0xf2a7: CupertinoIcons.chart_pie, // pie_chart_outline_outlined
  0xf2ae: CupertinoIcons.play, // play_arrow_outlined
  0xf2af: CupertinoIcons.play_circle, // play_circle_filled_outlined
  0xf2b0: CupertinoIcons.play_circle, // play_circle_outline_outlined
  0xf2b1: CupertinoIcons.play_circle, // play_circle_outlined
  0xf2b5: CupertinoIcons.text_badge_checkmark, // playlist_add_check_outlined
  0xf2b6: CupertinoIcons.text_badge_plus, // playlist_add_outlined
  0xf2b7: CupertinoIcons.music_note_list, // playlist_play_outlined
  0xf2d0: CupertinoIcons.shield_lefthalf_fill, // privacy_tip_outlined
  0xf2d4: CupertinoIcons.globe, // public_outlined
  0xf2d7: CupertinoIcons.pin, // push_pin_outlined
  0xf2d8: CupertinoIcons.qrcode, // qr_code_2_outlined
  0xf2da: CupertinoIcons.qrcode_viewfinder, // qr_code_scanner_outlined
  0xf2de: CupertinoIcons.music_note_list, // queue_music_outlined
  0xf2e5:
      CupertinoIcons.largecircle_fill_circle, // radio_button_checked_outlined
  0xf2e6: CupertinoIcons
      .circle, // radio_button_off_outlined / radio_button_unchecked_outlined
  0xf2ef: CupertinoIcons.doc_text, // receipt_long_outlined
  0xf2f7: CupertinoIcons.arrow_clockwise, // refresh_outlined
  0xf2f9: CupertinoIcons.minus_circle, // remove_circle_outline_outlined
  0xf2fe: CupertinoIcons.minus, // remove_outlined
  0xf305: CupertinoIcons.repeat, // repeat_outlined
  0xf306: CupertinoIcons.gobackward_10, // replay_10_outlined
  0xf30a: CupertinoIcons.gobackward, // replay_outlined
  0xf310: CupertinoIcons.exclamationmark_triangle, // report_problem_outlined
  0xf314: CupertinoIcons.arrow_counterclockwise, // restart_alt_outlined
  0xf318: CupertinoIcons.arrow_counterclockwise, // restore_outlined
  0xf325: CupertinoIcons.antenna_radiowaves_left_right, // router_outlined
  0xf333: CupertinoIcons.tray_arrow_down, // save_alt_outlined
  0xf334: CupertinoIcons.floppy_disk, // save_outlined
  0xf339: CupertinoIcons.clock, // schedule_outlined
  0xf33d: CupertinoIcons.lab_flask, // science_outlined
  0xf34b: CupertinoIcons.search, // search_outlined
  0xf34c: CupertinoIcons.shield, // security_outlined
  0xf350: CupertinoIcons.text_alignleft, // segment_outlined
  0xf353: CupertinoIcons.tag, // sell_outlined
  0xf355: CupertinoIcons.paperplane, // send_outlined
  0xf35a: CupertinoIcons.antenna_radiowaves_left_right, // sensors_outlined
  0xf364:
      CupertinoIcons.arrow_counterclockwise, // settings_backup_restore_outlined
  0xf36e: CupertinoIcons.gear, // settings_outlined
  0xf373: CupertinoIcons.gear, // settings_suggest_outlined
  0xf378: CupertinoIcons.share, // share_outlined
  0xf379: CupertinoIcons.shield, // shield_outlined
  0xf380: CupertinoIcons.text_alignleft, // short_text_outlined
  0xf382: CupertinoIcons.graph_square, // show_chart_outlined
  0xf3a0: CupertinoIcons.forward_end, // skip_next_outlined
  0xf3a1: CupertinoIcons.backward_end, // skip_previous_outlined
  0xf3a6: CupertinoIcons.play_rectangle, // smart_display_outlined
  0xf3a9: CupertinoIcons.device_phone_portrait, // smartphone_outlined
  0xf3b5: CupertinoIcons.textformat_abc, // sort_by_alpha_outlined
  0xf3b6: CupertinoIcons.sort_down, // sort_outlined
  0xf3b9: CupertinoIcons.arrow_down, // south_outlined
  0xf3c0: CupertinoIcons.text_bubble, // speaker_notes_outlined
  0xf3c3: CupertinoIcons.speedometer, // speed_outlined
  0xf3ca: CupertinoIcons.gamecontroller, // sports_esports_outlined
  0xf3d9: CupertinoIcons.chart_bar, // stacked_bar_chart_outlined
  0xf3dc: CupertinoIcons.star, // star_border_outlined
  0xf3df: CupertinoIcons.star, // star_outline_outlined
  0xf3e0: CupertinoIcons.star, // star_outlined
  0xf3e9: CupertinoIcons.stop_circle, // stop_circle_outlined
  0xf3ea: CupertinoIcons.stop, // stop_outlined
  0xf3f6: CupertinoIcons.paintbrush, // style_outlined
  0xf3f9: CupertinoIcons.text_alignleft, // subject_outlined
  0xf3fb: CupertinoIcons.rectangle_stack, // subscriptions_outlined
  0xf3fd: CupertinoIcons.captions_bubble, // subtitles_outlined
  0xf408: CupertinoIcons.arrow_right_arrow_left, // swap_horiz_outlined
  0xf409: CupertinoIcons
      .arrow_right_arrow_left_circle, // swap_horizontal_circle_outlined
  0xf40a: CupertinoIcons.arrow_up_arrow_down, // swap_vert_outlined
  0xf40c: CupertinoIcons.hand_draw, // swipe_outlined
  0xf412: CupertinoIcons.arrow_right_arrow_left, // sync_alt_outlined
  0xf414: CupertinoIcons.arrow_2_circlepath, // sync_outlined
  0xf419: CupertinoIcons.tray_arrow_down, // system_update_alt_outlined
  0xf41a: CupertinoIcons.tray_arrow_down, // system_update_outlined
  0xf424: CupertinoIcons.number, // tag_outlined
  0xf42c: CupertinoIcons.textformat, // text_fields_outlined
  0xf44a: CupertinoIcons.timer, // timer_outlined
  0xf44b: CupertinoIcons.textformat, // title_outlined
  0xf44d: CupertinoIcons.calendar_today, // today_outlined
  0xf453: CupertinoIcons.hand_point_right, // touch_app_outlined
  0xf45e: CupertinoIcons.globe, // translate_outlined
  0xf45f: CupertinoIcons.globe, // travel_explore_outlined
  0xf466: CupertinoIcons.slider_horizontal_3, // tune_outlined
  0xf46b: CupertinoIcons.tv, // tv_outlined
  0xf46f: CupertinoIcons.arrow_uturn_left, // undo_outlined
  0xf471: CupertinoIcons.chevron_up_chevron_down, // unfold_more_outlined
  0xf476: CupertinoIcons.arrow_clockwise, // update_outlined
  0xf478: CupertinoIcons.arrow_up_doc, // upload_file_outlined
  0xf479: CupertinoIcons.arrow_up_circle, // upload_outlined
  0xf47c: CupertinoIcons.checkmark_seal, // verified_outlined
  0xf47d: CupertinoIcons.checkmark_shield, // verified_user_outlined
  0xf47e: CupertinoIcons.arrow_down_to_line, // vertical_align_bottom_outlined
  0xf480: CupertinoIcons.arrow_up_to_line, // vertical_align_top_outlined
  0xf488: CupertinoIcons.film, // video_library_outlined
  0xf48c: CupertinoIcons.videocam, // videocam_outlined
  0xf48e: CupertinoIcons.gamecontroller, // videogame_asset_outlined
  0xf48f: CupertinoIcons.rectangle_grid_1x2, // view_agenda_outlined
  0xf492: CupertinoIcons.rectangle_split_3x1, // view_column_outlined
  0xf495: CupertinoIcons.rectangle_grid_1x2, // view_day_outlined
  0xf498: CupertinoIcons.list_bullet, // view_list_outlined
  0xf49b: CupertinoIcons.sidebar_left, // view_sidebar_outlined
  0xf49c: CupertinoIcons.rectangle_grid_1x2, // view_stream_outlined
  0xf4a0: CupertinoIcons.eye_slash, // visibility_off_outlined
  0xf4a1: CupertinoIcons.eye, // visibility_outlined
  0xf4a5: CupertinoIcons.speaker_1, // volume_down_outlined
  0xf4a7: CupertinoIcons.speaker_slash, // volume_off_outlined
  0xf4a8: CupertinoIcons.speaker_2, // volume_up_outlined
  0xf4aa: CupertinoIcons.lock, // vpn_key_outlined
  0xf4ae: CupertinoIcons.exclamationmark_triangle, // warning_amber_outlined
  0xf4af: CupertinoIcons.exclamationmark_triangle, // warning_outlined
  0xf4c0: CupertinoIcons.macwindow, // web_asset_outlined
  0xf4c7: CupertinoIcons.square_grid_2x2, // widgets_outlined
  0xf4d0:
      CupertinoIcons.antenna_radiowaves_left_right, // wifi_tethering_outlined
  0xf4dc: CupertinoIcons.zoom_in, // zoom_in_outlined
  0xf4dd:
      CupertinoIcons.arrow_up_left_arrow_down_right, // zoom_out_map_outlined
  0xf4de: CupertinoIcons.zoom_out, // zoom_out_outlined
  0xf522: CupertinoIcons.person_crop_circle_fill, // account_circle_rounded
  0xf52c: CupertinoIcons.plus_circle, // add_circle_outline_rounded
  0xf52d: CupertinoIcons.plus_circle_fill, // add_circle_rounded
  0xf530: CupertinoIcons.link, // add_link_rounded
  0xf534: CupertinoIcons.photo_on_rectangle, // add_photo_alternate_rounded
  0xf537: CupertinoIcons.add, // add_rounded
  0xf556: CupertinoIcons.text_alignleft, // align_horizontal_left_rounded
  0xf557: CupertinoIcons.text_alignright, // align_horizontal_right_rounded
  0xf55e: CupertinoIcons.arrow_branch, // alt_route_rounded
  0xf56f: CupertinoIcons.archivebox_fill, // archive_rounded
  0xf571: CupertinoIcons.chevron_back, // arrow_back_ios_rounded
  0xf572: CupertinoIcons.chevron_back, // arrow_back_rounded
  0xf575: CupertinoIcons.arrow_down, // arrow_downward_rounded
  0xf577: CupertinoIcons.chevron_down, // arrow_drop_down_rounded
  0xf578: CupertinoIcons.chevron_up, // arrow_drop_up_rounded
  0xf579: CupertinoIcons.chevron_forward, // arrow_forward_ios_rounded
  0xf57a: CupertinoIcons.chevron_forward, // arrow_forward_rounded
  0xf57b: CupertinoIcons.arrowtriangle_left_fill, // arrow_left_rounded
  0xf57d: CupertinoIcons.arrowtriangle_right_fill, // arrow_right_rounded
  0xf57e: CupertinoIcons.arrow_up, // arrow_upward_rounded
  0xf580: CupertinoIcons.doc_text_fill, // article_rounded
  0xf581: CupertinoIcons
      .rectangle_arrow_up_right_arrow_down_left, // aspect_ratio_rounded
  0xf593: CupertinoIcons.music_note, // audiotrack_rounded
  0xf596: CupertinoIcons.sparkles, // auto_awesome_rounded
  0xf598: CupertinoIcons.wand_stars, // auto_fix_high_rounded
  0xf59c: CupertinoIcons.book_fill, // auto_stories_rounded
  0xf59e: CupertinoIcons.arrow_2_circlepath, // autorenew_rounded
  0xf5a3: CupertinoIcons.cloud_upload_fill, // backup_rounded
  0xf5a5: CupertinoIcons.person_crop_rectangle_fill, // badge_rounded
  0xf5a9: CupertinoIcons.chart_bar_fill, // bar_chart_rounded
  0xf5be: CupertinoIcons.nosign, // block_rounded
  0xf5ca: CupertinoIcons.bolt_fill, // bolt_rounded
  0xf5cc: CupertinoIcons.book_fill, // book_rounded
  0xf5cd: CupertinoIcons.bookmark_fill, // bookmark_add_rounded
  0xf5cf: CupertinoIcons
      .bookmark, // bookmark_border_rounded / bookmark_outline_rounded
  0xf5d1: CupertinoIcons.bookmark_fill, // bookmark_rounded
  0xf5d2: CupertinoIcons.bookmark_fill, // bookmarks_rounded
  0xf5d6: CupertinoIcons.pencil, // border_color_rounded
  0xf5e6: CupertinoIcons.sun_max_fill, // brightness_6_rounded
  0xf5e7: CupertinoIcons.sun_max_fill, // brightness_7_rounded
  0xf5e8: CupertinoIcons.sun_max_fill, // brightness_auto_rounded
  0xf5e9: CupertinoIcons.sun_max_fill, // brightness_high_rounded
  0xf5ea: CupertinoIcons.sun_min, // brightness_low_rounded
  0xf5eb: CupertinoIcons.sun_max, // brightness_medium_rounded
  0xf5ef: CupertinoIcons.paintbrush_fill, // brush_rounded
  0xf5f1: CupertinoIcons.ant_fill, // bug_report_rounded
  0xf5f2: CupertinoIcons.wrench_fill, // build_circle_rounded
  0xf5fb: CupertinoIcons.arrow_2_circlepath, // cached_rounded
  0xf5fe: CupertinoIcons.calendar_today, // calendar_today_rounded
  0xf609: CupertinoIcons.arrow_branch, // call_split_rounded
  0xf60b: CupertinoIcons.camera_fill, // camera_alt_rounded
  0xf616: CupertinoIcons.xmark_circle_fill, // cancel_rounded
  0xf620: CupertinoIcons.tv_fill, // cast_connected_rounded
  0xf622: CupertinoIcons.tv, // cast_rounded
  0xf632: CupertinoIcons.square, // check_box_outline_blank_rounded
  0xf633: CupertinoIcons.checkmark_square_fill, // check_box_rounded
  0xf634: CupertinoIcons.checkmark_circle, // check_circle_outline_rounded
  0xf635: CupertinoIcons.checkmark_circle_fill, // check_circle_rounded
  0xf636: CupertinoIcons.checkmark, // check_rounded
  0xf637: CupertinoIcons.checkmark_square_fill, // checklist_rounded
  0xf63a: CupertinoIcons.chevron_left, // chevron_left_rounded
  0xf63b: CupertinoIcons.chevron_right, // chevron_right_rounded
  0xf63e: CupertinoIcons.book_fill, // chrome_reader_mode_rounded
  0xf640: CupertinoIcons.circle_fill, // circle_rounded
  0xf645: CupertinoIcons.xmark, // clear_rounded
  0xf646:
      CupertinoIcons.arrow_down_right_arrow_up_left, // close_fullscreen_rounded
  0xf647: CupertinoIcons.xmark, // close_rounded
  0xf64a: CupertinoIcons.captions_bubble_fill, // closed_caption_rounded
  0xf64c: CupertinoIcons.cloud_fill, // cloud_done_rounded
  0xf64d: CupertinoIcons.cloud_download_fill, // cloud_download_rounded
  0xf64e: CupertinoIcons.wifi_slash, // cloud_off_rounded
  0xf650: CupertinoIcons.cloud_fill, // cloud_rounded
  0xf651: CupertinoIcons.cloud_upload_fill, // cloud_upload_rounded
  0xf653: CupertinoIcons.chevron_left_slash_chevron_right, // code_rounded
  0xf656: CupertinoIcons.bookmark_fill, // collections_bookmark_rounded
  0xf657: CupertinoIcons.photo_on_rectangle, // collections_rounded
  0xf658: CupertinoIcons.paintbrush_fill, // color_lens_rounded
  0xf659: CupertinoIcons.eyedropper_full, // colorize_rounded
  0xf65d: CupertinoIcons.arrow_right_arrow_left, // compare_arrows_rounded
  0xf661: CupertinoIcons.desktopcomputer, // computer_rounded
  0xf66c: CupertinoIcons.doc_on_doc_fill, // content_copy_rounded / copy_rounded
  0xf66f: CupertinoIcons.doc_on_clipboard_fill, // content_paste_rounded
  0xf673: CupertinoIcons.doc_on_doc_fill, // copy_all_rounded
  0xf679: CupertinoIcons.folder_badge_plus, // create_new_folder_rounded
  0xf684: CupertinoIcons.viewfinder, // crop_free_rounded
  0xf689: CupertinoIcons.crop, // crop_rounded
  0xf68a: CupertinoIcons.square, // crop_square_rounded
  0xf68c: CupertinoIcons.moon_fill, // dark_mode_rounded
  0xf68d: CupertinoIcons.square_grid_2x2_fill, // dashboard_customize_rounded
  0xf68e: CupertinoIcons.square_grid_2x2_fill, // dashboard_rounded
  0xf692: CupertinoIcons.calendar, // date_range_rounded
  0xf694: CupertinoIcons.line_horizontal_3, // dehaze_rounded
  0xf695: CupertinoIcons.trash_fill, // delete_forever_rounded
  0xf696: CupertinoIcons.trash, // delete_outline_rounded
  0xf697: CupertinoIcons.trash_fill, // delete_rounded
  0xf698: CupertinoIcons.trash_fill, // delete_sweep_rounded
  0xf69b: CupertinoIcons.doc_text_fill, // description_rounded
  0xf69f: CupertinoIcons.desktopcomputer, // desktop_windows_rounded
  0xf6a7: CupertinoIcons.device_laptop, // devices_other_rounded
  0xf6a8: CupertinoIcons.device_laptop, // devices_rounded
  0xf6c1: CupertinoIcons.rectangle_grid_1x2_fill, // dns_rounded
  0xf6c8: CupertinoIcons.minus_circle_fill, // do_not_disturb_on_rounded
  0xf6ce: CupertinoIcons.doc_text_viewfinder, // document_scanner_rounded
  0xf6d2: CupertinoIcons.checkmark_alt, // done_all_rounded
  0xf6d4: CupertinoIcons.checkmark, // done_rounded
  0xf6dd: CupertinoIcons.checkmark_circle_fill, // download_done_rounded
  0xf6df: CupertinoIcons.arrow_down_circle_fill, // download_rounded
  0xf6e0: CupertinoIcons.arrow_down_circle_fill, // downloading_rounded
  0xf6e2: CupertinoIcons.line_horizontal_3, // drag_handle_rounded
  0xf6e3: CupertinoIcons.line_horizontal_3, // drag_indicator_rounded
  0xf6e5: CupertinoIcons.folder_fill, // drive_file_move_rounded
  0xf6e6: CupertinoIcons.square_pencil, // drive_file_rename_outline_rounded
  0xf6fb: CupertinoIcons.pencil, // edit_rounded
  0xf707: CupertinoIcons.rosette, // emoji_events_rounded
  0xf712: CupertinoIcons.exclamationmark_circle, // error_outline_rounded
  0xf713: CupertinoIcons.exclamationmark_circle_fill, // error_rounded
  0xf719: CupertinoIcons.calendar, // event_available_rounded
  0xf71b: CupertinoIcons.calendar, // event_note_rounded
  0xf71e: CupertinoIcons.square_arrow_right_fill, // exit_to_app_rounded
  0xf71f: CupertinoIcons.chevron_up, // expand_less_rounded
  0xf720: CupertinoIcons.chevron_down, // expand_more_rounded
  0xf724: CupertinoIcons.compass_fill, // explore_rounded
  0xf72c: CupertinoIcons.cube_box_fill, // extension_rounded
  0xf732: CupertinoIcons.doc_checkmark_fill, // fact_check_rounded
  0xf734: CupertinoIcons.forward_fill, // fast_forward_rounded
  0xf735: CupertinoIcons.backward_fill, // fast_rewind_rounded
  0xf737: CupertinoIcons.heart, // favorite_border_rounded
  0xf738: CupertinoIcons.heart_fill, // favorite_rounded
  0xf748: CupertinoIcons.arrow_down_doc_fill, // file_download_rounded
  0xf74a: CupertinoIcons.arrow_up_doc_fill, // file_upload_rounded
  0xf755: CupertinoIcons
      .line_horizontal_3_decrease_circle_fill, // filter_alt_rounded
  0xf756: CupertinoIcons.circle_lefthalf_fill, // filter_b_and_w_rounded
  0xf75b: CupertinoIcons.line_horizontal_3_decrease, // filter_list_rounded
  0xf75c: CupertinoIcons.square_on_square, // filter_none_rounded
  0xf765: CupertinoIcons.arrow_left_to_line, // first_page_rounded
  0xf766: CupertinoIcons
      .rectangle_arrow_up_right_arrow_down_left, // fit_screen_rounded
  0xf768: CupertinoIcons.flag_fill, // flag_rounded
  0xf77d: CupertinoIcons.folder_open, // folder_open_rounded
  0xf77e: CupertinoIcons.folder_fill, // folder_rounded
  0xf783: CupertinoIcons.textformat, // font_download_rounded
  0xf785: CupertinoIcons.text_aligncenter, // format_align_center_rounded
  0xf787: CupertinoIcons.text_alignleft, // format_align_left_rounded
  0xf788: CupertinoIcons.text_alignright, // format_align_right_rounded
  0xf789: CupertinoIcons.bold, // format_bold_rounded
  0xf78f: CupertinoIcons.increase_indent, // format_indent_increase_rounded
  0xf792: CupertinoIcons.list_bullet, // format_list_bulleted_rounded
  0xf793: CupertinoIcons.list_number, // format_list_numbered_rounded
  0xf796: CupertinoIcons.quote_bubble_fill, // format_quote_rounded
  0xf798: CupertinoIcons.textformat_size, // format_size_rounded
  0xf79d: CupertinoIcons.chat_bubble_2_fill, // forum_rounded
  0xf79e: CupertinoIcons.goforward_10, // forward_10_rounded
  0xf7a5: CupertinoIcons.fullscreen_exit, // fullscreen_exit_rounded
  0xf7a6: CupertinoIcons.fullscreen, // fullscreen_rounded
  0xf7aa: CupertinoIcons.gamecontroller_fill, // gamepad_rounded
  0xf7bd:
      CupertinoIcons.waveform, // graphic_eq_rounded / multitrack_audio_rounded
  0xf7c4: CupertinoIcons.square_grid_2x2_fill, // grid_view_rounded
  0xf7c6: CupertinoIcons.person_2_fill, // group_rounded
  0xf7da: CupertinoIcons.headphones, // headphones_rounded
  0xf7e2: CupertinoIcons.arrow_up_down, // height_rounded
  0xf7e4: CupertinoIcons.question_circle, // help_outline_rounded
  0xf7ef: CupertinoIcons.clock, // history_rounded
  0xf7f0: CupertinoIcons.clock, // history_toggle_off_rounded
  0xf7f5: CupertinoIcons.house_fill, // home_rounded
  0xf7f8: CupertinoIcons.minus, // horizontal_rule_rounded
  0xf7fe: CupertinoIcons.hourglass, // hourglass_empty_rounded
  0xf800: CupertinoIcons.hourglass, // hourglass_top_rounded
  0xf804:
      CupertinoIcons.person_crop_circle_badge_checkmark, // how_to_reg_rounded
  0xf80d: CupertinoIcons.photo_fill, // image_rounded
  0xf810: CupertinoIcons.book_fill, // import_contacts_rounded
  0xf815: CupertinoIcons.info_circle, // info_outline_rounded
  0xf816: CupertinoIcons.info_circle_fill, // info_rounded
  0xf819: CupertinoIcons.chart_bar_square_fill, // insert_chart_rounded
  0xf81b: CupertinoIcons.doc_fill, // insert_drive_file_rounded
  0xf820: CupertinoIcons.chart_bar_fill, // insights_rounded
  0xf822: CupertinoIcons.archivebox_fill, // inventory_2_rounded
  0xf825: CupertinoIcons.drop_fill, // invert_colors_rounded
  0xf826: CupertinoIcons.share, // ios_share_rounded
  0xf82a: CupertinoIcons.keyboard, // keyboard_alt_rounded
  0xf82b: CupertinoIcons.chevron_down, // keyboard_arrow_down_rounded
  0xf82c: CupertinoIcons.chevron_left, // keyboard_arrow_left_rounded
  0xf82d: CupertinoIcons.chevron_right, // keyboard_arrow_right_rounded
  0xf82e: CupertinoIcons.chevron_up, // keyboard_arrow_up_rounded
  0xf833: CupertinoIcons.keyboard, // keyboard_rounded
  0xf83c: CupertinoIcons.tag, // label_outline_rounded
  0xf83f: CupertinoIcons.globe, // language_rounded
  0xf844: CupertinoIcons.arrow_right_to_line, // last_page_rounded
  0xf848: CupertinoIcons.chart_bar_fill, // leaderboard_rounded
  0xf84e: CupertinoIcons.checkmark_square_fill, // library_add_check_rounded
  0xf84f: CupertinoIcons.plus_rectangle_on_rectangle, // library_add_rounded
  0xf850: CupertinoIcons.book_fill, // library_books_rounded
  0xf851: CupertinoIcons.music_albums_fill, // library_music_rounded
  0xf852: CupertinoIcons.sun_max_fill, // light_mode_rounded
  0xf854: CupertinoIcons.lightbulb, // lightbulb_outline_rounded
  0xf85a: CupertinoIcons.link, // link_rounded
  0xf85d: CupertinoIcons.list_bullet, // list_alt_rounded
  0xf85e: CupertinoIcons.list_bullet, // list_rounded
  0xf860: CupertinoIcons.tv_fill, // live_tv_rounded
  0xf86b: CupertinoIcons.flame_fill, // local_fire_department_rounded
  0xf887: CupertinoIcons.lock_open_fill, // lock_open_rounded
  0xf888: CupertinoIcons.lock, // lock_outline_rounded
  0xf889: CupertinoIcons.lock_fill, // lock_rounded
  0xf88a: CupertinoIcons.arrow_right_to_line, // login_rounded
  0xf88b: CupertinoIcons.square_arrow_right, // logout_rounded
  0xf89e: CupertinoIcons.person_crop_circle_fill, // manage_accounts_rounded
  0xf89f: CupertinoIcons.doc_text_search, // manage_search_rounded
  0xf8a8: CupertinoIcons.envelope_badge_fill, // mark_email_unread_rounded
  0xf8b4: CupertinoIcons.book_fill, // menu_book_rounded
  0xf8b5: CupertinoIcons.sidebar_left, // menu_open_rounded
  0xf8b7: CupertinoIcons.arrow_merge, // merge_type_rounded
  0xf8bb: CupertinoIcons.mic_fill, // mic_none_rounded
  0xf8bd: CupertinoIcons.mic_fill, // mic_rounded
  0xf8c0: CupertinoIcons.minus, // minimize_rounded
  0xf8d9: CupertinoIcons.ellipsis, // more_horiz_rounded
  0xf8dc: CupertinoIcons.ellipsis_vertical, // more_vert_rounded
  0xf8e4: CupertinoIcons.tray_arrow_down_fill, // move_to_inbox_rounded
  0xf8e5: CupertinoIcons.film_fill, // movie_creation_rounded
  0xf8e6: CupertinoIcons.film_fill, // movie_filter_rounded
  0xf8e7: CupertinoIcons.film_fill, // movie_rounded
  0xf8ed: CupertinoIcons.music_note, // music_note_rounded
  0xf8f0: CupertinoIcons.location_fill, // my_location_rounded
  0xf8fc: CupertinoIcons.wifi, // network_check_rounded
  0xf8ff: CupertinoIcons.tag_fill, // new_label_rounded
  0xf0020: CupertinoIcons.doc_append, // note_add_rounded
  0xf0026: CupertinoIcons.bell_fill, // notifications_active_rounded
  0xf0027: CupertinoIcons.bell_fill, // notifications_none_rounded
  0xf0028: CupertinoIcons.bell_slash_fill, // notifications_off_rounded
  0xf002a: CupertinoIcons.bell_fill, // notifications_rounded
  0xf0030: CupertinoIcons.drop_fill, // opacity_rounded
  0xf0032:
      CupertinoIcons.arrow_up_left_arrow_down_right, // open_in_full_rounded
  0xf0034: CupertinoIcons.arrow_up_right_square, // open_in_new_rounded
  0xf0035: CupertinoIcons.move, // open_with_rounded
  0xf0039: CupertinoIcons.tray_arrow_up_fill, // outbox_rounded
  0xf0041: CupertinoIcons.paintbrush_fill, // palette_rounded
  0xf0052: CupertinoIcons.pause_circle_fill, // pause_circle_filled_rounded
  0xf0053: CupertinoIcons.pause_circle, // pause_circle_outline_rounded
  0xf0056: CupertinoIcons.pause_fill, // pause_rounded
  0xf005c: CupertinoIcons.person_2_fill, // people_alt_rounded
  0xf005d: CupertinoIcons.person_2, // people_outline_rounded
  0xf0064: CupertinoIcons.photo_on_rectangle, // perm_media_rounded
  0xf0067: CupertinoIcons.person_badge_plus_fill, // person_add_alt_1_rounded
  0xf0068: CupertinoIcons.person_badge_plus_fill, // person_add_alt_rounded
  0xf006c: CupertinoIcons.person, // person_outline_rounded
  0xf0070: CupertinoIcons.person_badge_minus_fill, // person_remove_rounded
  0xf0071: CupertinoIcons.person_fill, // person_rounded
  0xf0078: CupertinoIcons.device_phone_portrait, // phone_android_rounded
  0xf008b: CupertinoIcons.camera_fill, // photo_camera_back_rounded
  0xf008d: CupertinoIcons.camera_fill, // photo_camera_rounded
  0xf008f: CupertinoIcons.photo_on_rectangle, // photo_library_rounded
  0xf0096: CupertinoIcons.doc_fill, // picture_as_pdf_rounded
  0xf0097:
      CupertinoIcons.rectangle_on_rectangle, // picture_in_picture_alt_rounded
  0xf0099: CupertinoIcons.chart_pie, // pie_chart_outline_rounded
  0xf00a0: CupertinoIcons.play_fill, // play_arrow_rounded
  0xf00a1: CupertinoIcons.play_circle_fill, // play_circle_filled_rounded
  0xf00a2: CupertinoIcons.play_circle, // play_circle_outline_rounded
  0xf00a3: CupertinoIcons.play_circle_fill, // play_circle_rounded
  0xf00a7: CupertinoIcons.text_badge_checkmark, // playlist_add_check_rounded
  0xf00a8: CupertinoIcons.text_badge_plus, // playlist_add_rounded
  0xf00a9: CupertinoIcons.music_note_list, // playlist_play_rounded
  0xf00c2: CupertinoIcons.shield_lefthalf_fill, // privacy_tip_rounded
  0xf00c6: CupertinoIcons.globe, // public_rounded
  0xf00c9: CupertinoIcons.pin_fill, // push_pin_rounded
  0xf00ca: CupertinoIcons.qrcode, // qr_code_2_rounded
  0xf00cc: CupertinoIcons.qrcode_viewfinder, // qr_code_scanner_rounded
  0xf00d0: CupertinoIcons.music_note_list, // queue_music_rounded
  0xf00d7:
      CupertinoIcons.largecircle_fill_circle, // radio_button_checked_rounded
  0xf00d8: CupertinoIcons
      .circle, // radio_button_off_rounded / radio_button_unchecked_rounded
  0xf00e1: CupertinoIcons.doc_text_fill, // receipt_long_rounded
  0xf00e9: CupertinoIcons.arrow_clockwise, // refresh_rounded
  0xf00eb: CupertinoIcons.minus_circle, // remove_circle_outline_rounded
  0xf00f1: CupertinoIcons.minus, // remove_rounded
  0xf00f7: CupertinoIcons.repeat, // repeat_rounded
  0xf00f8: CupertinoIcons.gobackward_10, // replay_10_rounded
  0xf00fc: CupertinoIcons.gobackward, // replay_rounded
  0xf0101:
      CupertinoIcons.exclamationmark_triangle_fill, // report_problem_rounded
  0xf0106: CupertinoIcons.arrow_counterclockwise, // restart_alt_rounded
  0xf010b: CupertinoIcons.arrow_counterclockwise, // restore_rounded
  0xf0117: CupertinoIcons.antenna_radiowaves_left_right, // router_rounded
  0xf0125: CupertinoIcons.tray_arrow_down_fill, // save_alt_rounded
  0xf0126: CupertinoIcons.floppy_disk, // save_rounded
  0xf012b: CupertinoIcons.clock_fill, // schedule_rounded
  0xf012f: CupertinoIcons.lab_flask, // science_rounded
  0xf013d: CupertinoIcons.search, // search_rounded
  0xf013e: CupertinoIcons.shield_fill, // security_rounded
  0xf0142: CupertinoIcons.text_alignleft, // segment_rounded
  0xf0145: CupertinoIcons.tag_fill, // sell_rounded
  0xf0147: CupertinoIcons.paperplane_fill, // send_rounded
  0xf014c: CupertinoIcons.antenna_radiowaves_left_right, // sensors_rounded
  0xf0156:
      CupertinoIcons.arrow_counterclockwise, // settings_backup_restore_rounded
  0xf0164: CupertinoIcons.gear, // settings_rounded
  0xf0165: CupertinoIcons.gear, // settings_suggest_rounded
  0xf016a: CupertinoIcons.share, // share_rounded
  0xf016b: CupertinoIcons.shield_fill, // shield_rounded
  0xf0172: CupertinoIcons.text_alignleft, // short_text_rounded
  0xf0174: CupertinoIcons.graph_square, // show_chart_rounded
  0xf0192: CupertinoIcons.forward_end_fill, // skip_next_rounded
  0xf0193: CupertinoIcons.backward_end_fill, // skip_previous_rounded
  0xf0198: CupertinoIcons.play_rectangle_fill, // smart_display_rounded
  0xf019b: CupertinoIcons.device_phone_portrait, // smartphone_rounded
  0xf01a7: CupertinoIcons.textformat_abc, // sort_by_alpha_rounded
  0xf01a8: CupertinoIcons.sort_down, // sort_rounded
  0xf01ab: CupertinoIcons.arrow_down, // south_rounded
  0xf01b2: CupertinoIcons.text_bubble_fill, // speaker_notes_rounded
  0xf01b5: CupertinoIcons.speedometer, // speed_rounded
  0xf01bc: CupertinoIcons.gamecontroller_fill, // sports_esports_rounded
  0xf01cb: CupertinoIcons.chart_bar_fill, // stacked_bar_chart_rounded
  0xf01cf: CupertinoIcons.star, // star_border_rounded
  0xf01d1: CupertinoIcons.star, // star_outline_rounded
  0xf01d4: CupertinoIcons.star_fill, // star_rounded
  0xf01db: CupertinoIcons.stop_circle_fill, // stop_circle_rounded
  0xf01dc: CupertinoIcons.stop_fill, // stop_rounded
  0xf01e8: CupertinoIcons.paintbrush_fill, // style_rounded
  0xf01eb: CupertinoIcons.text_alignleft, // subject_rounded
  0xf01ed: CupertinoIcons.rectangle_stack_fill, // subscriptions_rounded
  0xf01ef: CupertinoIcons.captions_bubble_fill, // subtitles_rounded
  0xf01fa: CupertinoIcons.arrow_right_arrow_left, // swap_horiz_rounded
  0xf01fb: CupertinoIcons
      .arrow_right_arrow_left_circle_fill, // swap_horizontal_circle_rounded
  0xf01fc: CupertinoIcons.arrow_up_arrow_down, // swap_vert_rounded
  0xf01fe: CupertinoIcons.hand_draw_fill, // swipe_rounded
  0xf0204: CupertinoIcons.arrow_right_arrow_left, // sync_alt_rounded
  0xf0207: CupertinoIcons.arrow_2_circlepath, // sync_rounded
  0xf020b: CupertinoIcons.tray_arrow_down, // system_update_alt_rounded
  0xf020c: CupertinoIcons.tray_arrow_down, // system_update_rounded
  0xf0216: CupertinoIcons.number, // tag_rounded
  0xf021e: CupertinoIcons.textformat, // text_fields_rounded
  0xf023c: CupertinoIcons.timer_fill, // timer_rounded
  0xf023d: CupertinoIcons.textformat, // title_rounded
  0xf023f: CupertinoIcons.calendar_today, // today_rounded
  0xf0245: CupertinoIcons.hand_point_right_fill, // touch_app_rounded
  0xf0250: CupertinoIcons.globe, // translate_rounded
  0xf0251: CupertinoIcons.globe, // travel_explore_rounded
  0xf0258: CupertinoIcons.slider_horizontal_3, // tune_rounded
  0xf025d: CupertinoIcons.tv_fill, // tv_rounded
  0xf0261: CupertinoIcons.arrow_uturn_left, // undo_rounded
  0xf0263: CupertinoIcons.chevron_up_chevron_down, // unfold_more_rounded
  0xf0268: CupertinoIcons.arrow_clockwise, // update_rounded
  0xf026a: CupertinoIcons.arrow_up_doc_fill, // upload_file_rounded
  0xf026b: CupertinoIcons.arrow_up_circle_fill, // upload_rounded
  0xf026e: CupertinoIcons.checkmark_seal_fill, // verified_rounded
  0xf026f: CupertinoIcons.checkmark_shield_fill, // verified_user_rounded
  0xf0270: CupertinoIcons.arrow_down_to_line, // vertical_align_bottom_rounded
  0xf0272: CupertinoIcons.arrow_up_to_line, // vertical_align_top_rounded
  0xf027a: CupertinoIcons.film_fill, // video_library_rounded
  0xf027e: CupertinoIcons.videocam_fill, // videocam_rounded
  0xf0280: CupertinoIcons.gamecontroller_fill, // videogame_asset_rounded
  0xf0281: CupertinoIcons.rectangle_grid_1x2_fill, // view_agenda_rounded
  0xf0284: CupertinoIcons.rectangle_split_3x1_fill, // view_column_rounded
  0xf0287: CupertinoIcons.rectangle_grid_1x2_fill, // view_day_rounded
  0xf028a: CupertinoIcons.list_bullet, // view_list_rounded
  0xf028d: CupertinoIcons.sidebar_left, // view_sidebar_rounded
  0xf028e: CupertinoIcons.rectangle_grid_1x2_fill, // view_stream_rounded
  0xf0292: CupertinoIcons.eye_slash_fill, // visibility_off_rounded
  0xf0293: CupertinoIcons.eye_fill, // visibility_rounded
  0xf0297: CupertinoIcons.speaker_1_fill, // volume_down_rounded
  0xf0299: CupertinoIcons.speaker_slash_fill, // volume_off_rounded
  0xf029a: CupertinoIcons.speaker_2_fill, // volume_up_rounded
  0xf029c: CupertinoIcons.lock_fill, // vpn_key_rounded
  0xf02a0: CupertinoIcons.exclamationmark_triangle, // warning_amber_rounded
  0xf02a1: CupertinoIcons.exclamationmark_triangle_fill, // warning_rounded
  0xf02b2: CupertinoIcons.macwindow, // web_asset_rounded
  0xf02b9: CupertinoIcons.square_grid_2x2_fill, // widgets_rounded
  0xf02c2:
      CupertinoIcons.antenna_radiowaves_left_right, // wifi_tethering_rounded
  0xf02ce: CupertinoIcons.zoom_in, // zoom_in_rounded
  0xf02cf:
      CupertinoIcons.arrow_up_left_arrow_down_right, // zoom_out_map_rounded
  0xf02d0: CupertinoIcons.zoom_out, // zoom_out_rounded
  0xf02d4: CupertinoIcons.cursor_rays, // ads_click_rounded
  0xf02de: CupertinoIcons.music_note, // audio_file_rounded
  0xf02e8: CupertinoIcons.arrow_2_circlepath, // cloud_sync_rounded
  0xf02ef: CupertinoIcons.doc_on_clipboard_fill, // content_paste_go_rounded
  0xf02f0: CupertinoIcons.doc_text_search, // content_paste_search_rounded
  0xf02f1: CupertinoIcons.circle_lefthalf_fill, // contrast_rounded
  0xf0318: CupertinoIcons.doc_fill, // file_open_rounded
  0xf0335: CupertinoIcons.circle_grid_hex_fill, // hub_rounded
  0xf0343: CupertinoIcons.lock, // key_rounded
  0xf0344: CupertinoIcons.command, // keyboard_command_key_rounded
  0xf0347: CupertinoIcons.chevron_left_2, // keyboard_double_arrow_left_rounded
  0xf0348:
      CupertinoIcons.chevron_right_2, // keyboard_double_arrow_right_rounded
  0xf0354: CupertinoIcons.waveform_path_ecg, // monitor_heart_rounded
  0xf0359: CupertinoIcons.number, // numbers_rounded
  0xf035a: CupertinoIcons.square_arrow_right_fill, // output_rounded
  0xf0365:
      CupertinoIcons.checkmark_circle_fill, // playlist_add_check_circle_rounded
  0xf0377: CupertinoIcons.arrow_branch, // route_rounded
  0xf039d: CupertinoIcons.textformat_size, // text_decrease_rounded
  0xf039e: CupertinoIcons.textformat_size, // text_increase_rounded
  0xf03ab: CupertinoIcons.film_fill, // video_file_rounded
  0xf03ba: CupertinoIcons.wifi, // wifi_find_rounded
  0xf03c7: CupertinoIcons.cursor_rays, // ads_click_sharp
  0xf03d1: CupertinoIcons.music_note, // audio_file_sharp
  0xf03db: CupertinoIcons.arrow_2_circlepath, // cloud_sync_sharp
  0xf03e2: CupertinoIcons.doc_on_clipboard_fill, // content_paste_go_sharp
  0xf03e3: CupertinoIcons.doc_text_search, // content_paste_search_sharp
  0xf03e4: CupertinoIcons.circle_lefthalf_fill, // contrast_sharp
  0xf040b: CupertinoIcons.doc_fill, // file_open_sharp
  0xf0428: CupertinoIcons.circle_grid_hex_fill, // hub_sharp
  0xf0436: CupertinoIcons.lock, // key_sharp
  0xf0437: CupertinoIcons.command, // keyboard_command_key_sharp
  0xf043a: CupertinoIcons.chevron_left_2, // keyboard_double_arrow_left_sharp
  0xf043b: CupertinoIcons.chevron_right_2, // keyboard_double_arrow_right_sharp
  0xf0447: CupertinoIcons.waveform_path_ecg, // monitor_heart_sharp
  0xf044c: CupertinoIcons.number, // numbers_sharp
  0xf044d: CupertinoIcons.square_arrow_right_fill, // output_sharp
  0xf0458:
      CupertinoIcons.checkmark_circle_fill, // playlist_add_check_circle_sharp
  0xf046a: CupertinoIcons.arrow_branch, // route_sharp
  0xf0490: CupertinoIcons.textformat_size, // text_decrease_sharp
  0xf0491: CupertinoIcons.textformat_size, // text_increase_sharp
  0xf049e: CupertinoIcons.film_fill, // video_file_sharp
  0xf04ad: CupertinoIcons.wifi, // wifi_find_sharp
  0xf04ba: CupertinoIcons.cursor_rays, // ads_click
  0xf04c4: CupertinoIcons.music_note, // audio_file
  0xf04ce: CupertinoIcons.arrow_2_circlepath, // cloud_sync
  0xf04d6: CupertinoIcons.doc_on_clipboard_fill, // content_paste_go
  0xf04d7: CupertinoIcons.doc_text_search, // content_paste_search
  0xf04d8: CupertinoIcons.circle_lefthalf_fill, // contrast
  0xf04ff: CupertinoIcons.doc_fill, // file_open
  0xf051d: CupertinoIcons.circle_grid_hex_fill, // hub
  0xf051f: CupertinoIcons.calendar, // calendar_month_outlined
  0xf052b: CupertinoIcons.lock, // key
  0xf052d: CupertinoIcons.command, // keyboard_command_key
  0xf0530: CupertinoIcons.chevron_left_2, // keyboard_double_arrow_left
  0xf0531: CupertinoIcons.chevron_right_2, // keyboard_double_arrow_right
  0xf053d: CupertinoIcons.waveform_path_ecg, // monitor_heart
  0xf0542: CupertinoIcons.number, // numbers
  0xf0543: CupertinoIcons.square_arrow_right_fill, // output
  0xf054f: CupertinoIcons.checkmark_circle_fill, // playlist_add_check_circle
  0xf0561: CupertinoIcons.arrow_branch, // route
  0xf058a: CupertinoIcons.textformat_size, // text_decrease
  0xf058b: CupertinoIcons.textformat_size, // text_increase
  0xf0598: CupertinoIcons.film_fill, // video_file
  0xf05a8: CupertinoIcons.wifi, // wifi_find
  0xf05b5: CupertinoIcons.cursor_rays, // ads_click_outlined
  0xf05bf: CupertinoIcons.music_note, // audio_file_outlined
  0xf05c9: CupertinoIcons.arrow_2_circlepath, // cloud_sync_outlined
  0xf05d0: CupertinoIcons.doc_on_clipboard, // content_paste_go_outlined
  0xf05d1: CupertinoIcons.doc_text_search, // content_paste_search_outlined
  0xf05d2: CupertinoIcons.circle_lefthalf_fill, // contrast_outlined
  0xf05f9: CupertinoIcons.doc, // file_open_outlined
  0xf0616: CupertinoIcons.circle_grid_hex, // hub_outlined
  0xf0624: CupertinoIcons.lock, // key_outlined
  0xf0625: CupertinoIcons.command, // keyboard_command_key_outlined
  0xf0628: CupertinoIcons.chevron_left_2, // keyboard_double_arrow_left_outlined
  0xf0629:
      CupertinoIcons.chevron_right_2, // keyboard_double_arrow_right_outlined
  0xf0635: CupertinoIcons.waveform_path_ecg, // monitor_heart_outlined
  0xf063a: CupertinoIcons.number, // numbers_outlined
  0xf063b: CupertinoIcons.square_arrow_right, // output_outlined
  0xf0646:
      CupertinoIcons.checkmark_circle, // playlist_add_check_circle_outlined
  0xf0658: CupertinoIcons.arrow_branch, // route_outlined
  0xf067e: CupertinoIcons.textformat_size, // text_decrease_outlined
  0xf067f: CupertinoIcons.textformat_size, // text_increase_outlined
  0xf068c: CupertinoIcons.film, // video_file_outlined
  0xf069b: CupertinoIcons.wifi, // wifi_find_outlined
  0xf06ae: CupertinoIcons.calendar, // calendar_month_sharp
  0xf06bb: CupertinoIcons.calendar, // calendar_month
  0xf06c8: CupertinoIcons.calendar, // calendar_month_rounded
  0xf06f9: CupertinoIcons.music_note_list, // lyrics_outlined
  0xf0751: CupertinoIcons.music_note_list, // lyrics_sharp
  0xf07a9: CupertinoIcons.music_note_list, // lyrics
  0xf0801: CupertinoIcons.music_note_list, // lyrics_rounded
};
