const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
// The Dart test pipes the generated card-back player in on stdin; no path or
// code ever arrives through argv. Executing that generated code is this
// harness's whole purpose.
const script = fs.readFileSync(0, 'utf8');

function required(value, message) {
  if (value == null) throw new assert.AssertionError({message});
  return value;
}

function exercise(autoplay, native = false, previous = false) {
  const listeners = new Map();
  const observers = [];
  const source = {isConnected: true, after(e) {e.isConnected = true; e.previousSibling = this;}};
  const original = {getAttribute() {return 'clip.webm';}};
  source.content = {textContent: '', querySelector(s) {
    if (s.includes(',')) return original;
    return s === 'video[src]' ? (native ? null : original) : (native ? {} : null);
  }};
  const currentText = {content: {textContent: 'Existing source information on an old card', querySelector() {return null;}}};
  const copies = Array.from({length: 3}, () => ({pauseCount: 0, pause() {this.pauseCount++;}, removeAttribute() {}}));
  const nativeButton = {clicks: 0, click() {this.clicks++;}, getClientRects() {return [];}};
  const host = {isConnected: true, dataset: {placement: 'bottom', autoplay: String(autoplay)}, children: [],
    appendChild(e) {this.children.push(e);}, contains(e) {return this.children.includes(e);}};
  const doc = {
    getElementById(id) {return id === 'fushi-video-player' ? host : source;},
    querySelectorAll(s) {
      if (s === 'template[data-fushi-video-source]') return previous ? [currentText, source] : [source];
      if (s === '*') return [];
      if (s.startsWith('video.fushi-inline-video')) return copies;
      if (s.startsWith('.fushi-synced-sentence-media')) return [nativeButton];
      return [];
    },
    createElement(tag) {return {tag, style: {}, plays: 0, pauses: 0, currentTime: 9,
      setAttribute() {}, play() {this.plays++; return Promise.resolve();}, pause() {this.pauses++;}};},
  };
  const win = {addEventListener(k,v) {listeners.set(k,v);}, removeEventListener(k) {listeners.delete(k);}};
  class Observer {
    constructor(fn) {this.fn=fn;this.disconnected=false;this.roots=[];observers.push(this);}
    observe(root) {this.roots.push(root);}
    disconnect() {this.disconnected=true;}
  }
  const context = vm.createContext({window: win, document: doc, MutationObserver: Observer, WeakSet});
  vm.runInContext(script, context); // NOSONAR: test harness runs the player script generated by the Dart test under test
  assert(copies.every(e => e.hidden && e.pauseCount === 1), 'all old copies must be silent');
  const replay = required(host.children.find(e => e.tag === 'button'), 'replay button is installed');
  if (native) {
    replay.onclick();
    assert.equal(nativeButton.clicks, 1, 'native replay works even when template hides its native link');
  } else {
    const video = required(host.children.find(e => e.tag === 'video'), 'managed player is installed');
    assert.equal(video.plays, autoplay ? 1 : 0, 'autoplay is opt-in and starts exactly once');
    video.currentTime=1;
    replay.onclick();
    assert.equal(video.currentTime, 0);
    assert.equal(video.plays, autoplay ? 2 : 1, 'replay must use the same player');
    source.isConnected=false;
    observers[0].fn();
    assert.equal(video.pauses, 1, 'changing the card stops playback');
    assert(observers[0].disconnected, 'changing the card disconnects observation');
    assert.equal(listeners.size, 0, 'changing the card releases pagehide handler');
    win.__fushiVideoCleanup();
    assert.equal(video.pauses, 1, 'cleanup is idempotent');
  }
}
exercise(true);
exercise(false);
exercise(true, true);
exercise(true, false, true);
